### ISSUE TITLE
"Top500" Example error

### ISSUE THREAD

**Issue by weirdarrow** [JCMais/node-libcurl#11]
Hi,

the "top500" example code gives me the following error:

/home/myuser/Projects/MyProject/node_modules/node-libcurl/lib/Curl.js:326
    return this._setOpt( optionIdOrName, optionValue );
                ^
**Error: Unknown option given. First argument must be the option internal id or the option name. You can use the Curl.option constants.**
    at Curl.setOpt (/home/myuser/Projects/MyProject/node_modules/node-libcurl/lib/Curl.js:326:17)
    at doRequest (/home/myuser/Projects/MyProject/top500.js:39:10)
    at Object.<anonymous> (/home/myuser/Projects/MyProject/top500.js:18:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

The line the gives the error is:
```
    curl.setOpt( Curl.option.PRIVATE, siteUrl );
```

Is the PRIVATE option supported? You're writing in http://curl-library.cool.haxx.narkive.com/bFH3TXjM/add-node-js-binding

> Here is the current list of options not implemented:
>
> -- Options related to pass data around (Not needed because of the nature of javascript).
> PROGRESSDATA, XFERINFODATA, DEBUGDATA, **PRIVATE**, etc.

Thanks a lot,
Gy.

**Comment by JCMais** [comment]
You are correct, it's not supported!

It was in the beginning but I've removed it since it's not needed, you can just declare:

    curl.siteUrl = ...

I will fix that in the next release, which I'm working on right now.
