### ISSUE TITLE
was compiled against a different Node.js version using

### ISSUE THREAD

**Issue by gsion** [JCMais/node-libcurl#117]
was compiled against a different Node.js version using
NODE_MODULE_VERSION 59. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)

**Comment by JCMais** [comment]
You are trying to use this module with Electron, please follow the instructions on the Readme.

If you already did, let me know which commands you used.

**Comment by JCMais** [comment]
Closing this since it works

**Comment by ernanielyjr** [comment]
Same problem to use with NWjs on MacOS.

I did:

```
npm install -g nw-gyp
npm install -g node-pre-gyp

export npm_config_target=0.29.4
export npm_config_arch=x64
export npm_config_target_arch=x64
export npm_config_runtime=node-webkit
export npm_config_build_from_source=true
export npm_config_node_gyp=$(which nw-gyp)

npm i node-libcurl --save
```

And get this error:

```
node-libcurl WARN Could not finish postinstall
node-libcurl ERR! Error: Command failed: node "/Users/ejay/workspaces/sicredi/woop-desktop/node_modules/node-libcurl/lib/Curl.js"
internal/modules/cjs/loader.js:718
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '/Users/ejay/workspaces/sicredi/woop-desktop/node_modules/node-libcurl/lib/binding/node_libcurl.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 59. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/ejay/workspaces/sicredi/woop-desktop/node_modules/node-libcurl/lib/Curl.js:28:15)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
```
