### ISSUE TITLE
Error Installing on RHEL 7.5 - libcurl-gnutls.so.4: cannot open shared object file

### ISSUE THREAD

**Issue by kresss** [JCMais/node-libcurl#128]
When installing on RHEL 7.5 I get an error that libcurl-gnutls is not found. I checked and that shared object library is not valid for RHEL. 

Any help would be appreciated.

My current versions are: 

node-libcurl@1.3.2 

$ npm version
{ mcs: '4.2.0',
  npm: '3.10.10',
  ares: '1.10.1-DEV',
  http_parser: '2.7.1',
  icu: '50.1.2',
  modules: '48',
  napi: '3',
  node: '6.14.2',
  openssl: '1.0.2k-fips',
  uv: '1.19.2',
  v8: '5.1.281.111',
  zlib: '1.2.7' }

$ rpm -qa | grep curl
libcurl-devel-7.29.0-46.el7.x86_64
curl-7.29.0-46.el7.x86_64
python-pycurl-7.19.0-19.el7.x86_64
libcurl-7.29.0-46.el7.x86_64

npm install error:

```
node-libcurl WARN Could not finish postinstall 
node-libcurl ERR! Error: Command failed: node "/home/kresss/GIT/MCS/wsm/mcs/node_modules/node-libcurl/lib/Curl.js"
module.js:604
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: libcurl-gnutls.so.4: cannot open shared object file: No such file or directory
    at Error (native)
    at Object.Module._extensions..node (module.js:604:18)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/kresss/GIT/MCS/wsm/mcs/node_modules/node-libcurl/lib/Curl.js:28:15)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
```

**Comment by JCMais** [comment]
can you try installing without the prebuilt binaries?

```
npm i node-libcurl --build-from-source
```

**Comment by kresss** [comment]
That seems to work. My npm output is bellow. 

```
$ npm i node-libcurl --build-from-source

> node-libcurl@1.3.2 install /home/kresss/newtest/node_modules/node-libcurl
> node-pre-gyp install --fallback-to-build

make: Entering directory `/home/kresss/newtest/node_modules/node-libcurl/build'
  CXX(target) Release/obj.target/node_libcurl/src/node_libcurl.o
  CXX(target) Release/obj.target/node_libcurl/src/Easy.o
  CXX(target) Release/obj.target/node_libcurl/src/Share.o
  CXX(target) Release/obj.target/node_libcurl/src/Multi.o
  CXX(target) Release/obj.target/node_libcurl/src/Curl.o
  CXX(target) Release/obj.target/node_libcurl/src/CurlHttpPost.o
  SOLINK_MODULE(target) Release/obj.target/node_libcurl.node
  COPY Release/node_libcurl.node
  COPY /home/kresss/newtest/node_modules/node-libcurl/lib/binding/node_libcurl.node
  TOUCH Release/obj.target/action_after_build.stamp
make: Leaving directory `/home/kresss/newtest/node_modules/node-libcurl/build'

> node-libcurl@1.3.2 postinstall /home/kresss/newtest/node_modules/node-libcurl
> node scripts/postinstall

/home/kresss/newtest
└─┬ node-libcurl@1.3.2 
  ├─┬ debug@2.6.9 
  │ └── ms@2.0.0 
  ├─┬ fs-extra@4.0.3 
  │ ├── graceful-fs@4.1.11 
  │ ├── jsonfile@4.0.0 
  │ └── universalify@0.1.1 
  ├── nan@2.8.0 
  ├─┬ node-gyp@3.6.3 
  │ ├─┬ fstream@1.0.11 
  │ │ └── inherits@2.0.3 
  │ ├─┬ glob@7.1.2 
  │ │ ├── fs.realpath@1.0.0 
  │ │ ├─┬ inflight@1.0.6 
  │ │ │ └── wrappy@1.0.2 
  │ │ ├── once@1.4.0 
  │ │ └── path-is-absolute@1.0.1 
  │ ├─┬ minimatch@3.0.4 
  │ │ └─┬ brace-expansion@1.1.11 
  │ │   ├── balanced-match@1.0.0 
  │ │   └── concat-map@0.0.1 
  │ ├─┬ mkdirp@0.5.1 
  │ │ └── minimist@0.0.8 
  │ ├─┬ nopt@3.0.6 
  │ │ └── abbrev@1.1.1 
  │ ├─┬ osenv@0.1.5 
  │ │ ├── os-homedir@1.0.2 
  │ │ └── os-tmpdir@1.0.2 
  │ ├─┬ request@2.81.0 
  │ │ ├── aws-sign2@0.6.0 
  │ │ ├── aws4@1.7.0 
  │ │ ├── caseless@0.12.0 
  │ │ ├─┬ combined-stream@1.0.6 
  │ │ │ └── delayed-stream@1.0.0 
  │ │ ├── extend@3.0.1 
  │ │ ├── forever-agent@0.6.1 
  │ │ ├─┬ form-data@2.1.4 
  │ │ │ └── asynckit@0.4.0 
  │ │ ├─┬ har-validator@4.2.1 
  │ │ │ ├─┬ ajv@4.11.8 
  │ │ │ │ ├── co@4.6.0 
  │ │ │ │ └─┬ json-stable-stringify@1.0.1 
  │ │ │ │   └── jsonify@0.0.0 
  │ │ │ └── har-schema@1.0.5 
  │ │ ├─┬ hawk@3.1.3 
  │ │ │ ├── boom@2.10.1 
  │ │ │ ├── cryptiles@2.0.5 
  │ │ │ ├── hoek@2.16.3 
  │ │ │ └── sntp@1.0.9 
  │ │ ├─┬ http-signature@1.1.1 
  │ │ │ ├── assert-plus@0.2.0 
  │ │ │ ├─┬ jsprim@1.4.1 
  │ │ │ │ ├── assert-plus@1.0.0 
  │ │ │ │ ├── extsprintf@1.3.0 
  │ │ │ │ ├── json-schema@0.2.3 
  │ │ │ │ └─┬ verror@1.10.0 
  │ │ │ │   └── assert-plus@1.0.0 
  │ │ │ └─┬ sshpk@1.14.2 
  │ │ │   ├── asn1@0.2.3 
  │ │ │   ├── assert-plus@1.0.0 
  │ │ │   ├── bcrypt-pbkdf@1.0.1 
  │ │ │   ├─┬ dashdash@1.14.1 
  │ │ │   │ └── assert-plus@1.0.0 
  │ │ │   ├── ecc-jsbn@0.1.1 
  │ │ │   ├─┬ getpass@0.1.7 
  │ │ │   │ └── assert-plus@1.0.0 
  │ │ │   ├── jsbn@0.1.1 
  │ │ │   ├── safer-buffer@2.1.2 
  │ │ │   └── tweetnacl@0.14.5 
  │ │ ├── is-typedarray@1.0.0 
  │ │ ├── isstream@0.1.2 
  │ │ ├── json-stringify-safe@5.0.1 
  │ │ ├─┬ mime-types@2.1.18 
  │ │ │ └── mime-db@1.33.0 
  │ │ ├── oauth-sign@0.8.2 
  │ │ ├── performance-now@0.2.0 
  │ │ ├── qs@6.4.0 
  │ │ ├── safe-buffer@5.1.2 
  │ │ ├── stringstream@0.0.6 
  │ │ ├─┬ tough-cookie@2.3.4 
  │ │ │ └── punycode@1.4.1 
  │ │ ├── tunnel-agent@0.6.0 
  │ │ └── uuid@3.2.1 
  │ ├── rimraf@2.6.2 
  │ ├── semver@5.3.0 
  │ ├─┬ tar@2.2.1 
  │ │ └── block-stream@0.0.9 
  │ └─┬ which@1.3.1 
  │   └── isexe@2.0.0 
  ├─┬ node-pre-gyp@0.6.39 
  │ ├── detect-libc@1.0.3 
  │ ├─┬ hawk@3.1.3 
  │ │ ├─┬ boom@2.10.1 
  │ │ │ └── hoek@2.16.3 
  │ │ ├── cryptiles@2.0.5 
  │ │ ├── hoek@2.16.3 
  │ │ └─┬ sntp@1.0.9 
  │ │   └── hoek@2.16.3 
  │ ├─┬ mkdirp@0.5.1 
  │ │ └── minimist@0.0.8 
  │ ├─┬ nopt@4.0.1 
  │ │ ├── abbrev@1.1.1 
  │ │ └─┬ osenv@0.1.4 
  │ │   ├── os-homedir@1.0.2 
  │ │   └── os-tmpdir@1.0.2 
  │ ├─┬ npmlog@4.1.2 
  │ │ ├─┬ are-we-there-yet@1.1.4 
  │ │ │ └── delegates@1.0.0 
  │ │ ├── console-control-strings@1.1.0 
  │ │ ├─┬ gauge@2.7.4 
  │ │ │ ├── aproba@1.2.0 
  │ │ │ ├── has-unicode@2.0.1 
  │ │ │ ├── object-assign@4.1.1 
  │ │ │ ├── signal-exit@3.0.2 
  │ │ │ ├─┬ string-width@1.0.2 
  │ │ │ │ ├── code-point-at@1.1.0 
  │ │ │ │ └─┬ is-fullwidth-code-point@1.0.0 
  │ │ │ │   └── number-is-nan@1.0.1 
  │ │ │ ├─┬ strip-ansi@3.0.1 
  │ │ │ │ └── ansi-regex@2.1.1 
  │ │ │ └── wide-align@1.1.2 
  │ │ └── set-blocking@2.0.0 
  │ ├─┬ rc@1.2.4 
  │ │ ├── deep-extend@0.4.2 
  │ │ ├── ini@1.3.5 
  │ │ ├── minimist@1.2.0 
  │ │ └── strip-json-comments@2.0.1 
  │ ├─┬ request@2.81.0 
  │ │ ├── aws-sign2@0.6.0 
  │ │ ├── aws4@1.6.0 
  │ │ ├── caseless@0.12.0 
  │ │ ├─┬ combined-stream@1.0.5 
  │ │ │ └── delayed-stream@1.0.0 
  │ │ ├── extend@3.0.1 
  │ │ ├── forever-agent@0.6.1 
  │ │ ├─┬ form-data@2.1.4 
  │ │ │ └── asynckit@0.4.0 
  │ │ ├─┬ har-validator@4.2.1 
  │ │ │ ├─┬ ajv@4.11.8 
  │ │ │ │ ├── co@4.6.0 
  │ │ │ │ └─┬ json-stable-stringify@1.0.1 
  │ │ │ │   └── jsonify@0.0.0 
  │ │ │ └── har-schema@1.0.5 
  │ │ ├─┬ http-signature@1.1.1 
  │ │ │ ├── assert-plus@0.2.0 
  │ │ │ ├─┬ jsprim@1.4.1 
  │ │ │ │ ├── assert-plus@1.0.0 
  │ │ │ │ ├── extsprintf@1.3.0 
  │ │ │ │ ├── json-schema@0.2.3 
  │ │ │ │ └─┬ verror@1.10.0 
  │ │ │ │   └── extsprintf@1.4.0 
  │ │ │ └─┬ sshpk@1.13.1 
  │ │ │   ├── asn1@0.2.3 
  │ │ │   ├── bcrypt-pbkdf@1.0.1 
  │ │ │   ├── dashdash@1.14.1 
  │ │ │   ├── ecc-jsbn@0.1.1 
  │ │ │   ├── getpass@0.1.7 
  │ │ │   ├── jsbn@0.1.1 
  │ │ │   └── tweetnacl@0.14.5 
  │ │ ├── is-typedarray@1.0.0 
  │ │ ├── isstream@0.1.2 
  │ │ ├── json-stringify-safe@5.0.1 
  │ │ ├─┬ mime-types@2.1.17 
  │ │ │ └── mime-db@1.30.0 
  │ │ ├── oauth-sign@0.8.2 
  │ │ ├── performance-now@0.2.0 
  │ │ ├── qs@6.4.0 
  │ │ ├── safe-buffer@5.1.1 
  │ │ ├── stringstream@0.0.5 
  │ │ ├─┬ tough-cookie@2.3.3 
  │ │ │ └── punycode@1.4.1 
  │ │ ├── tunnel-agent@0.6.0 
  │ │ └── uuid@3.2.1 
  │ ├─┬ rimraf@2.6.2 
  │ │ └─┬ glob@7.1.2 
  │ │   ├── fs.realpath@1.0.0 
  │ │   ├── inflight@1.0.6 
  │ │   ├─┬ minimatch@3.0.4 
  │ │   │ └─┬ brace-expansion@1.1.8 
  │ │   │   ├── balanced-match@1.0.0 
  │ │   │   └── concat-map@0.0.1 
  │ │   └── path-is-absolute@1.0.1 
  │ ├── semver@5.5.0 
  │ ├─┬ tar@2.2.1 
  │ │ ├── block-stream@0.0.9 
  │ │ ├─┬ fstream@1.0.11 
  │ │ │ └── graceful-fs@4.1.11 
  │ │ └── inherits@2.0.3 
  │ └─┬ tar-pack@3.4.1 
  │   ├── fstream-ignore@1.0.5 
  │   ├─┬ once@1.4.0 
  │   │ └── wrappy@1.0.2 
  │   ├─┬ readable-stream@2.3.3 
  │   │ ├── core-util-is@1.0.2 
  │   │ ├── isarray@1.0.0 
  │   │ ├── process-nextick-args@1.0.7 
  │   │ ├── string_decoder@1.0.3 
  │   │ └── util-deprecate@1.0.2 
  │   └── uid-number@0.0.6 
  ├─┬ npmlog@4.0.2 
  │ ├─┬ are-we-there-yet@1.1.5 
  │ │ ├── delegates@1.0.0 
  │ │ └─┬ readable-stream@2.3.6 
  │ │   ├── core-util-is@1.0.2 
  │ │   ├── isarray@1.0.0 
  │ │   ├── process-nextick-args@2.0.0 
  │ │   ├── string_decoder@1.1.1 
  │ │   └── util-deprecate@1.0.2 
  │ ├── console-control-strings@1.1.0 
  │ ├─┬ gauge@2.7.4 
  │ │ ├── aproba@1.2.0 
  │ │ ├── has-unicode@2.0.1 
  │ │ ├── object-assign@4.1.1 
  │ │ ├── signal-exit@3.0.2 
  │ │ ├─┬ string-width@1.0.2 
  │ │ │ ├── code-point-at@1.1.0 
  │ │ │ └─┬ is-fullwidth-code-point@1.0.0 
  │ │ │   └── number-is-nan@1.0.1 
  │ │ ├─┬ strip-ansi@3.0.1 
  │ │ │ └── ansi-regex@2.1.1 
  │ │ └── wide-align@1.1.3 
  │ └── set-blocking@2.0.0 
  └── prettier@1.13.5 

```
