### ISSUE TITLE
Callback not called with node 10.9.0

### ISSUE THREAD

**Issue by no-more** [JCMais/node-libcurl#147]
Hello,

I've just upgraded from node 8.9.4 to node 10.9.0 and node-libcurl (1.2.0 -> 1.3.3) does not seems to work anymore.
None of my curl.on('xxx', callback) is trigerred. I even tried with the default example : 
```
var Curl = require('node-libcurl').Curl;
 
var curl = new Curl();
 
curl.setOpt('URL', 'www.google.com');
curl.setOpt('FOLLOWLOCATION', true);
 
curl.on('end', function(statusCode, body, headers) {
 
    console.info(statusCode);
    console.info('---');
    console.info(body.length);
    console.info('---');
    console.info(this.getInfo( 'TOTAL_TIME'));
 
    this.close();
});
 
curl.on('error', curl.close.bind(curl));
curl.perform();
```

with no more success. There's no error, no timeout. The process just ends without calling the provided callback functions.
Maybe I'm doing something wrong but I don't know what that could be.

Thanks for any help.

**Comment by JCMais** [comment]
if you change the Node.js version, you need to rebuild the installed native addons, otherwise they are going to mostly crash with a segfault.

**Comment by no-more** [comment]
I removed completely my node_modules and lock files before reinstalling them (I think but I'm not sure I even clear the yarn cache before).

Is there another way to force rebuild ?

**Comment by JCMais** [comment]
what S.O. are you running?

You can build from source, `npm install node-libcurl --build-from-source`

**Comment by no-more** [comment]
Sorry but what is S.O. ?

I have rollback to node 8.9 but I'll try this tomorrow if I can. A full reinstall take me at least 3 hours.

**Comment by JCMais** [comment]
Operational System, sorry, had it backwards.

**Comment by no-more** [comment]
I'm on Windows 10.

**Comment by no-more** [comment]
When trying to build from source I have this error: 
```
1461 warn test-tool-package@0.1.1-beta.22 No description
1462 warn test-tool-package@0.1.1-beta.22 No repository field.
1463 verbose stack Error: node-libcurl@1.3.3 install: `node-pre-gyp install --fallback-to-build`
1463 verbose stack Exit status 1
1463 verbose stack     at EventEmitter.<anonymous> (C:\Users\chris\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:304:16)
1463 verbose stack     at EventEmitter.emit (events.js:182:13)
1463 verbose stack     at ChildProcess.<anonymous> (C:\Users\chris\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
1463 verbose stack     at ChildProcess.emit (events.js:182:13)
1463 verbose stack     at maybeClose (internal/child_process.js:961:16)
1463 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:250:5)
1464 verbose pkgid node-libcurl@1.3.3
1465 verbose cwd S:\test-tool-package
1466 verbose Windows_NT 10.0.17134
1467 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\nomore\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-libcurl" "--build-from-source"
1468 verbose node v10.9.0
1469 verbose npm  v6.4.0
1470 error code ELIFECYCLE
1471 error errno 1
1472 error node-libcurl@1.3.3 install: `node-pre-gyp install --fallback-to-build`
1472 error Exit status 1
1473 error Failed at the node-libcurl@1.3.3 install script.
1473 error This is probably not a problem with npm. There is likely additional logging output above.
1474 verbose exit [ 1, true ]
```

**Comment by JCMais** [comment]
can you place the whole log?

**Comment by JCMais** [comment]
This should be fixed on v2, currently available as `node-libcurl@next`
