### ISSUE TITLE
Unknown option `RTSP_REQUEST`

### ISSUE THREAD

**Issue by edykim** [JCMais/node-libcurl#159]
Thanks for the great library. I'd like to use it for RTSP request via CURL.

```js
curl.setOpt('RTSP_REQUEST', Curl.rtspreq.OPTIONS); // 1
curl.setOpt(Curl.option.RTSP_REQUEST, Curl.rtspreq.OPTIONS); // 2
```

1 and 2 return an unkown option error like below.

```js
Error: Unknown option given. First argument must be the option internal id or the option name. You can use the Curl.option constants.
    at Curl.setOpt (/path/to/node_modules/node-libcurl/lib/Curl.js:980:11)
    at Object.<anonymous> (/path/to/rt.js:11:6)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:752:3)
```

I couldn't find the constraint `RTSP_REQUEST` from the repository except for the API doc. Could you guide me on this issue?

**Comment by JCMais** [comment]
Hi @edykim , unfortunately I've forgotten to include this option, will do so later this week.

**Comment by JCMais** [comment]
This option will be available on the next version of the library, v2. Sorry for taking so long 😄 

There is a prerelease version available using the `next` tag: `node-libcurl@next`
