### ISSUE TITLE
Can't compile with iojs

### ISSUE THREAD

**Issue by voltagex** [JCMais/node-libcurl#16]
The build log is 129kb, but here's the important part
```
d:\git\mine\curl\node_modules\node-libcurl\node_modules\nan\nan_implementation_12_inl.h(181): error C2660: 'v8::Signature::New' : function does not take 4 arguments (..\src\Curl.cc) [d:\Git\Mine\curl\node_modules\node-libcurl\build\node-libcurl.vcxproj]
d:\git\mine\curl\node_modules\node-libcurl\node_modules\nan\nan_implementation_12_inl.h(181): error C2660: 'v8::Signature::New' : function does not take 4 arguments (..\src\node-libcurl.cc) [d:\Git\Mine\curl\node_modules\node-libcurl\build\node-libcurl.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\iojs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:169:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1009:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\iojs\\node.exe" "C:\\Program Files\\iojs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd d:\Git\Mine\curl\node_modules\node-libcurl
gyp ERR! node -v v2.0.1
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\iojs\\node.exe" "C:\\Program Files\\iojs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-libcurl"
npm ERR! node v2.0.1
npm ERR! npm  v2.9.0
npm ERR! code ELIFECYCLE

npm ERR! node-libcurl@0.3.0 install: `node tools/retrieve-win-deps && node tools/generate-stubs && node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-libcurl@0.3.0 install script 'node tools/retrieve-win-deps && node tools/generate-stubs && node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-libcurl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node tools/retrieve-win-deps && node tools/generate-stubs && node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-libcurl
npm ERR! There is likely additional logging output above.
```

I'm assuming that it's not supported but I thought I'd raise an issue anyway.

**Comment by JCMais** [comment]
Update [nan](https://github.com/rvagg/nan) should fix this. I will do that next week or so.

**Comment by JCMais** [comment]
Ok, so I was testing support for io.js and I was able to get it compiled without doing nothing special to the library, I just had to install one module responsible for getting the io.js header files (since node-gyp was trying to get them from http://nodejs.org/):
`npm install -g node-gyp-install`
`node-gyp-install`
`npm install node-libcurl`

This only works with io.js version < 2.

**Comment by kkoopa** [comment]
https://github.com/rvagg/pangyp

**Comment by JCMais** [comment]
@kkoopa I saw that fork too, but I didn't saw a way to use it without intervention from the user (the user still needs to install it globally, or I'm missing something?).

**Comment by kkoopa** [comment]
It can be installed locally.

**Comment by markmuir87** [comment]
I ran into this problem as well. Installing libcurl4-openssl-dev fixed it for me on Ubuntu. Have no idea why though, just a suggestion I stumbled across on stackoverflow.

**Comment by JCMais** [comment]
@markmuir87 this library needs the libcurl header files to build, those files are in the module you installed.

**Comment by JCMais** [comment]
iojs is now fully supported.
