### ISSUE TITLE
`yarn pregyp build` fails on macOS

### ISSUE THREAD

**Issue by sznowicki** [JCMais/node-libcurl#180]
I'm trying to help with #177 and I'm following the instructions on CONTRIBUTING.md. 

Sadly it fails to either build or rebuild C++ code.

You can find the output of `yarn pregyp build` below.

Do I need some additional dependencies on my machine? If so, I'd be more than happy to update CONTRIBUTING.md with that information.

```
szymon@MacBook-Air-Szymon node-libcurl (develop) $ yarn pregyp rebuild
yarn run v1.13.0
$ node-pre-gyp rebuild
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.13.0
node-pre-gyp info using node@10.2.1 | darwin | x64
gyp info it worked if it ends with ok
gyp info using node-gyp@4.0.0
gyp info using node@10.2.1 | darwin | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@4.0.0
gyp info using node@10.2.1 | darwin | x64
gyp info spawn /usr/bin/python
gyp info spawn args [ '/Users/szymon/dev/node-libcurl/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/szymon/dev/node-libcurl/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/szymon/dev/node-libcurl/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/szymon/.node-gyp/10.2.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/szymon/.node-gyp/10.2.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/szymon/dev/node-libcurl/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/szymon/.node-gyp/10.2.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/szymon/dev/node-libcurl',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@4.0.0
gyp info using node@10.2.1 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/node_libcurl/src/node_libcurl.o
clang: error: no such file or directory: '/usr/include'
make: *** [Release/obj.target/node_libcurl/src/node_libcurl.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/szymon/dev/node-libcurl/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Darwin 18.6.0
```

**Comment by JCMais** [comment]
Hi @sznowicki , thanks for trying to Contribute!

Check if this helps: https://github.com/JCMais/node-libcurl#xcode--10--macos-mojave

**Comment by sznowicki** [comment]
Sounds interesting. Sadly the .pkg file is missing on my machine (checked, have Xcode 10 and 10.14 macOS).

I'll try to check what's going on.

**Comment by sznowicki** [comment]
Solved all of my problems regarding build by installing Command Line Tools and then following your README section.

It's of course my fault I didn't notice there's a troubleshooting section in the README. Somehow in my head I expected to find it in the contributing file. To avoid similar issues I propose adding a hint right next to the "how to build" information in the CONTRIBUTING.md (see PR).

**Comment by JCMais** [comment]
Glad you got it figured, and thanks for improving the Contributing!
