### ISSUE TITLE
mojave unable to install

### ISSUE THREAD

**Issue by shirshak55** [JCMais/node-libcurl#208]
```
[10/19] ⠂ bcrypt
[13/19] ⠂ sharp
[14/19] ⠂ node-libcurl
[11/19] ⠄ sqlite3
error /Users/quantum/Desktop/code/vendure/node_modules/node-libcurl: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: /Users/quantum/Desktop/code/vendure/node_modules/node-libcurl
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.13.0
node-pre-gyp info using node@13.10.1 | darwin | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "/Users/quantum/Desktop/code/vendure/node_modules/node-libcurl/lib/binding/node_libcurl.node" (not found)
node-pre-gyp http GET https://github.com/JCMais/node-libcurl/releases/download/v2.0.2/node_libcurl-v2.0.2-node-v79-darwin-x64-unknown.tar.gz
node-pre-gyp http 404 https://github.com/JCMais/node-libcurl/releases/download/v2.0.2/node_libcurl-v2.0.2-node-v79-darwin-x64-unknown.tar.gz
node-pre-gyp WARN Tried to download(404): https://github.com/JCMais/node-libcurl/releases/download/v2.0.2/node_libcurl-v2.0.2-node-v79-darwin-x64-unknown.tar.gz
node-pre-gyp WARN Pre-built binaries not found for node-libcurl@2.0.2 and node@13.10.1 (node-v79 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://github.com/JCMais/node-libcurl/releases/download/v2.0.2/node_libcurl-v2.0.2-node-v79-darwin-x64-unknown.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@13.10.1 | darwin | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@13.10.1 | darwin | x64
gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [
gyp info spawn args   '/Users/quantum/Desktop/code/vendure/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/quantum/Desktop/code/vendure/node_modules/node-libcurl/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/quantum/Desktop/code/vendure/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/quantum/Library/Caches/node-gyp/13.10.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/quantum/Library/Caches/node-gyp/13.10.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/quantum/Desktop/code/vendure/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/quantum/Library/Caches/node-gyp/13.10.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/quantum/Desktop/code/vendure/node_modules/node-libcurl',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@13.10.1 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/node_libcurl/src/node_libcurl.o
clang: error: no such file or directory: '/usr/include'
make: *** [Release/obj.target/node_libcurl/src/node_libcurl.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/quantum/Desktop/code/vendure/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:316:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.3.0
gyp ERR! command "/usr/local/Cellar/node/13.10.1/bin/node" "/Users/quantum/Desktop/code/vendure/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/quantum/Desktop/code/vendure/node_modules/node-libcurl/lib/binding/node_libcurl.node" "--module_name=node_libcurl" "--module_path=/Users/quantum/Desktop/code/vendure/node_modules/node-libcurl/lib/binding" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v79"
gyp ERR! cwd /Users/quantum/Desktop/code/vendure/node_modules/node-libcurl
gyp ERR! node -v v13.10.1
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/13.10.1/bin/node /Users/quantum/Desktop/code/vendure/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/quantum/Desktop/code/vendure/node_modules/node-libcurl/lib/binding/node_libcurl.node --module_name=node_libcurl --module_path=/Users/quantum/Desktop/code/vendure/node_modules/node-libcurl/lib/binding --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/quantum/Desktop/code/vendure/node_modules/node-libcurl/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:316:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1026:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Darwin 19.3.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/13.10.1/bin/node" "/Users/quantum/Desktop/code/vendure/node_modules/node-libcurl/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/quantum/Desktop/code/vendure/node_modules/node-libcurl
node-pre-gyp ERR! node -v v13.10.1
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok

```

i tried to fix by 
```
open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg
```

but it says 
```
The file /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg does not exist.
```

**Comment by shirshak55** [comment]
upgraded to Catalina same issue.

**Comment by JCMais** [comment]
Please see the README, there is a section for this error: https://github.com/JCMais/node-libcurl#building-on-macos

**Comment by shirshak55** [comment]
@JCMais  its not working thats the problem. There is no such file `/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg`.

**Comment by JCMais** [comment]
Have you installed Xcode Command Line Tools?

You need to have the dev header files available in `/usr/include`. I don't have a macOS available right now to test how to retrieve it on the latest OS version.

**Comment by shirshak55** [comment]
@JCMais I have xcode installed

In fact here is result
```
$ xcode-select -p
/Library/Developer/CommandLineTools
```
Here is directory structure
```
➜  CommandLineTools cd /Library/Developer/CommandLineTools
➜  CommandLineTools ls
Library SDKs    usr
➜  CommandLineTools ls -al
total 0
drwxr-xr-x  5 root  wheel  160 Mar 13 19:01 .
drwxr-xr-x  4 root  wheel  128 Mar 13 19:04 ..
drwxr-xr-x  6 root  wheel  192 Sep  6  2019 Library
drwxr-xr-x  5 root  wheel  160 Mar 13 19:04 SDKs
drwxr-xr-x  7 root  wheel  224 Sep  6  2019 usr
```

**Comment by JCMais** [comment]
See if any of these fixes the issue:
https://stackoverflow.com/a/58436450/710693
https://apple.stackexchange.com/a/372600

**Comment by dantium** [comment]
I'm also seeing this error with Mac OSX 10.15.3

> See if any of these fixes the issue:
> https://stackoverflow.com/a/58436450/710693
> https://apple.stackexchange.com/a/372600

These didn't seem to work for me, it still produces the same error.

**Comment by JCMais** [comment]
@dantium @shirshak55 

what is the output of running
```shell
ls -al "$(xcrun --show-sdk-path)/usr/include"
```

?

**Comment by shirshak55** [comment]
```
git:(master) ✗ ls -al "$(xcrun --show-sdk-path)/usr/include"
total 3128
drwxr-xr-x  270 root  wheel    8640 Mar 13 19:04 .
drwxr-xr-x    7 root  wheel     224 Aug 30  2019 ..
-rw-r--r--    1 root  wheel   48946 Aug 24  2019 AppleTextureEncoder.h
-rw-r--r--    1 root  wheel   59503 Nov  7 11:37 AssertMacros.h
-rw-r--r--    1 root  wheel   24737 Nov  7 11:37 Availability.h
-rw-r--r--    1 root  wheel  431917 Nov  7 22:47 AvailabilityInternal.h
-rw-r--r--    1 root  wheel  211345 Nov  7 11:37 AvailabilityMacros.h
-rw-r--r--    1 root  wheel    6311 Aug 28  2019 AvailabilityVersions.h
-rw-r--r--    1 root  wheel    1775 Aug 24  2019 Block.h
drwxr-xr-x   11 root  wheel     352 Mar 13 19:03 CommonCrypto
-rw-r--r--    1 root  wheel   26422 Nov  7 11:37 ConditionalMacros.h
-rw-r--r--    1 root  wheel    1133 Aug 24  2019 Darwin.apinotes
drwxr-xr-x    7 root  wheel     224 Mar 13 19:03 EndpointSecurity
-rw-r--r--    1 root  wheel   31737 Nov  7 11:37 MacTypes.h
-rw-r--r--    1 root  wheel    5060 Aug 24  2019 NSSystemDirectories.h
-rw-r--r--    1 root  wheel   20481 Nov  7 22:47 TargetConditionals.h
-r--r--r--    1 root  wheel   27271 Aug 24  2019 Xplugin.h
-rw-r--r--    1 root  wheel    2291 Aug 24  2019 __cxxabi_config.h
-r--r--r--    1 root  wheel    2760 Oct  9 09:35 __wctype.h
-r--r--r--    1 root  wheel    1068 Oct  9 09:35 _ctermid.h
-r--r--r--    1 root  wheel   10408 Oct  9 09:35 _ctype.h
-r--r--r--    1 root  wheel    2718 Oct  9 09:35 _locale.h
-r--r--r--    1 root  wheel    5130 Oct  9 09:35 _regex.h
-r--r--r--    1 root  wheel    6201 Oct  9 09:35 _stdio.h
drwxr-xr-x   11 root  wheel     352 Mar 13 19:03 _types
-r--r--r--    1 root  wheel    2237 Oct  9 09:35 _types.h
-r--r--r--    1 root  wheel    3791 Oct  9 09:35 _wctype.h
-r--r--r--    1 root  wheel    1237 Oct  9 09:35 _xlocale.h
-r--r--r--    1 root  wheel    1214 Oct  9 09:35 aio.h
-r--r--r--    1 root  wheel    1435 Aug 24  2019 aliasdb.h
-r--r--r--    1 root  wheel    1376 Oct  9 09:35 alloca.h
drwxr-xr-x  116 root  wheel    3712 Mar 13 19:03 apache2
drwxr-xr-x   73 root  wheel    2336 Mar 13 19:03 apr-1
-r--r--r--    1 root  wheel    2901 Oct  9 09:35 ar.h
drwxr-xr-x    5 root  wheel     160 Mar 13 19:03 architecture
drwxr-xr-x    8 root  wheel     256 Mar 13 19:04 arpa
-rw-r--r--    1 root  wheel   49386 Sep 24  2019 asl.h
-r--r--r--    1 root  wheel    4239 Oct  9 09:35 assert.h
drwxr-xr-x    5 root  wheel     160 Mar 13 19:03 atm
drwxr-xr-x    3 root  wheel      96 Mar 13 19:03 bank
-r--r--r--    1 root  wheel    5084 Oct  9 09:35 bitstring.h
-r--r--r--    1 root  wheel    1556 Aug 24  2019 bootparams.h
-rw-r--r--    1 root  wheel    3356 Sep 27  2019 bootstrap.h
drwxr-xr-x   14 root  wheel     448 Mar 13 19:03 bsm
-rw-r--r--    1 root  wheel    6245 Aug 24  2019 bzlib.h
-rw-r--r--    1 root  wheel   12110 Aug 24  2019 cache.h
-rw-r--r--    1 root  wheel    1478 Aug 24  2019 cache_callbacks.h
-rw-r--r--    1 root  wheel   19340 Aug 24  2019 checkint.h
-rw-r--r--    1 root  wheel    3095 Aug 24  2019 com_err.h
-rw-r--r--    1 root  wheel    6362 Aug 24  2019 complex.h
-rw-r--r--    1 root  wheel   17921 Aug 24  2019 compression.h
-rw-r--r--    1 root  wheel    4336 Aug 24  2019 copyfile.h
drwxr-xr-x    3 root  wheel      96 Mar 13 19:03 corpses
-r--r--r--    1 root  wheel    2466 Oct  9 09:35 cpio.h
-r--r--r--    1 root  wheel    1588 Oct  9 09:35 crt_externs.h
-r--r--r--    1 root  wheel    3444 Oct  9 09:35 ctype.h
drwxr-xr-x   17 root  wheel     544 Mar 13 19:03 cups
drwxr-xr-x   10 root  wheel     320 Mar 13 19:03 curl
-rw-r--r--    1 root  wheel   80104 Aug 24  2019 curses.h
-rw-r--r--    1 root  wheel    7038 Aug 24  2019 cxxabi.h
-r--r--r--    1 root  wheel    7897 Oct  9 09:35 db.h
drwxr-xr-x    3 root  wheel      96 Mar 13 19:03 default_pager
drwxr-xr-x    6 root  wheel     192 Mar 13 19:03 device
-r--r--r--    1 root  wheel    7108 Oct  9 09:35 dirent.h
-r--r--r--    1 root  wheel    2590 Oct  9 09:35 disktab.h
drwxr-xr-x   17 root  wheel     544 Mar 13 19:03 dispatch
-rw-r--r--    1 root  wheel    3196 Sep 26  2019 dlfcn.h
-rw-r--r--    1 root  wheel    5675 Sep 25  2019 dns.h
-rw-r--r--    1 root  wheel  138340 Sep 24  2019 dns_sd.h
-rw-r--r--    1 root  wheel    7972 Sep 25  2019 dns_util.h
-rw-r--r--    1 root  wheel   26884 Sep 26  2019 dtrace.h
drwxr-xr-x    3 root  wheel      96 Mar 13 19:03 editline
-r--r--r--    1 root  wheel    4444 Oct  9 09:35 err.h
-r--r--r--    1 root  wheel    1003 Oct  9 09:35 errno.h
-rw-r--r--    1 root  wheel    2891 Aug 24  2019 eti.h
-r--r--r--    1 root  wheel    1968 Oct  9 09:35 execinfo.h
-rw-r--r--    1 root  wheel   43566 Aug 24  2019 expat.h
-rw-r--r--    1 root  wheel    5532 Aug 24  2019 expat_external.h
-r--r--r--    1 root  wheel    1002 Oct  9 09:35 fcntl.h
-rw-r--r--    1 root  wheel   18958 Aug 24  2019 fenv.h
drwxr-xr-x    8 root  wheel     256 Mar 13 19:03 ffi
-rw-r--r--    1 root  wheel    4047 Aug 24  2019 float.h
-r--r--r--    1 root  wheel    2831 Oct  9 09:35 fmtmsg.h
-r--r--r--    1 root  wheel    3602 Oct  9 09:35 fnmatch.h
-rw-r--r--    1 root  wheel   17190 Aug 24  2019 form.h
-r--r--r--    1 root  wheel    2540 Oct  9 09:35 fsproperties.h
-r--r--r--    1 root  wheel    3220 Oct  9 09:35 fstab.h
-r--r--r--    1 root  wheel    7856 Oct  9 09:35 fts.h
-r--r--r--    1 root  wheel    2291 Oct  9 09:35 ftw.h
-r--r--r--    1 root  wheel    1339 Oct  9 09:35 get_compat.h
-rw-r--r--    1 root  wheel    1878 Oct 10 11:00 gethostuuid.h
-r--r--r--    1 root  wheel    3260 Oct  9 09:35 getopt.h
-r--r--r--    1 root  wheel    5396 Oct  9 09:35 glob.h
-r--r--r--    1 root  wheel    3574 Aug 24  2019 grp.h
drwxr-xr-x    5 root  wheel     160 Mar 13 19:03 gssapi
-rw-r--r--    1 root  wheel     118 Aug 24  2019 gssapi.h
drwxr-xr-x    5 root  wheel     160 Mar 13 19:03 hfs
drwxr-xr-x    3 root  wheel      96 Mar 13 19:03 hid
-rw-r--r--    1 root  wheel    9246 Aug 24  2019 histedit.h
drwxr-xr-x   16 root  wheel     512 Mar 13 19:03 i386
-r--r--r--    1 root  wheel    8295 Aug 24  2019 iconv.h
-r--r--r--    1 root  wheel    2381 Aug 24  2019 ifaddrs.h
-r--r--r--    1 root  wheel    8821 Oct  9 09:35 inttypes.h
-r--r--r--    1 root  wheel    1852 Oct  9 09:35 iso646.h
drwxr-xr-x    6 root  wheel     192 Mar 13 19:03 kern
drwxr-xr-x    5 root  wheel     160 Mar 13 19:03 krb5
-rw-r--r--    1 root  wheel     338 Aug 24  2019 krb5.h
-r--r--r--    1 root  wheel    3820 Oct  9 09:35 langinfo.h
-rw-r--r--    1 root  wheel   15671 Sep 27  2019 launch.h
-rw-r--r--    1 root  wheel   25607 Aug 24  2019 lber.h
-rw-r--r--    1 root  wheel    1468 Aug 24  2019 lber_types.h
-rw-r--r--    1 root  wheel   89753 Aug 24  2019 ldap.h
-rw-r--r--    1 root  wheel    9466 Aug 24  2019 ldap_cdefs.h
-rw-r--r--    1 root  wheel    1814 Aug 24  2019 ldap_features.h
-rw-r--r--    1 root  wheel    9450 Aug 24  2019 ldap_schema.h
-rw-r--r--    1 root  wheel    3468 Aug 24  2019 ldap_utf8.h
-rw-r--r--    1 root  wheel    4674 Aug 24  2019 ldif.h
-r--r--r--    1 root  wheel    2012 Oct  9 09:35 libc.h
-r--r--r--    1 root  wheel    1550 Aug 24  2019 libcharset.h
drwxr-xr-x    6 root  wheel     192 Mar 13 19:03 libexslt
-r--r--r--    1 root  wheel    2326 Oct  9 09:35 libgen.h
drwxr-xr-x   16 root  wheel     512 Mar 13 19:03 libkern
-rw-r--r--    1 root  wheel    6532 Oct 10 11:00 libproc.h
-rw-r--r--    1 root  wheel    9564 Aug 24  2019 libunwind.h
drwxr-xr-x    4 root  wheel     128 Mar 13 19:03 libxml2
drwxr-xr-x   24 root  wheel     768 Mar 13 19:03 libxslt
-r--r--r--    1 root  wheel    5910 Oct  9 09:35 limits.h
-r--r--r--    1 root  wheel    1569 Aug 24  2019 localcharset.h
-r--r--r--    1 root  wheel    2288 Oct  9 09:35 locale.h
drwxr-xr-x  116 root  wheel    3712 Mar 13 19:03 mach
drwxr-xr-x   21 root  wheel     672 Mar 13 19:03 mach-o
drwxr-xr-x   11 root  wheel     352 Mar 13 19:03 mach_debug
drwxr-xr-x   15 root  wheel     480 Mar 13 19:03 machine
drwxr-xr-x    4 root  wheel     128 Mar 13 19:03 malloc
-rw-r--r--    1 root  wheel   32279 Aug 24  2019 math.h
-r--r--r--    1 root  wheel    8889 Aug 24  2019 membership.h
-r--r--r--    1 root  wheel    1893 Oct  9 09:35 memory.h
-rw-r--r--    1 root  wheel   11845 Aug 24  2019 menu.h
drwxr-xr-x    5 root  wheel     160 Aug 30  2019 miscfs
-rw-r--r--    1 root  wheel   27835 Aug 24  2019 module.modulemap
-r--r--r--    1 root  wheel    1826 Oct  9 09:35 monetary.h
-r--r--r--    1 root  wheel    2348 Oct  9 09:35 monitor.h
-r--r--r--    1 root  wheel    4138 Oct  9 09:35 mpool.h
-rw-r--r--    1 root  wheel   22018 Sep 25  2019 nameser.h
-rw-r--r--    1 root  wheel    3947 Aug 24  2019 nc_tparm.h
lrwxr-xr-x    1 root  wheel       8 Mar 13 19:03 ncurses.h -> curses.h
-rw-r--r--    1 root  wheel    3898 Aug 24  2019 ncurses_dll.h
-r--r--r--    1 root  wheel    4464 Oct  9 09:35 ndbm.h
drwxr-xr-x   19 root  wheel     608 Mar 13 19:03 net
drwxr-xr-x   19 root  wheel     608 Mar 13 19:03 net-snmp
-r--r--r--    1 root  wheel   12820 Aug 24  2019 netdb.h
drwxr-xr-x   24 root  wheel     768 Mar 13 19:03 netinet
drwxr-xr-x   11 root  wheel     352 Mar 13 19:03 netinet6
drwxr-xr-x    3 root  wheel      96 Mar 13 19:03 netkey
drwxr-xr-x   15 root  wheel     480 Mar 13 19:03 nfs
-r--r--r--    1 root  wheel    3457 Oct  9 09:35 nl_types.h
-r--r--r--    1 root  wheel    3434 Oct  9 09:35 nlist.h
-rw-r--r--    1 root  wheel   13411 Aug 24  2019 notify.h
-rw-r--r--    1 root  wheel    3379 Aug 24  2019 notify_keys.h
-r--r--r--    1 root  wheel    1209 Aug 24  2019 ntsid.h
drwxr-xr-x   21 root  wheel     672 Mar 13 19:03 objc
drwxr-xr-x   11 root  wheel     352 Mar 13 19:03 odmodule
drwxr-xr-x   13 root  wheel     416 Mar 13 19:03 os
-rw-r--r--    1 root  wheel    3770 Aug 24  2019 panel.h
-r--r--r--    1 root  wheel    4199 Oct  9 09:35 paths.h
drwxr-xr-x   11 root  wheel     352 Mar 13 19:03 pcap
-rw-r--r--    1 root  wheel    2294 Oct 18 04:45 pcap-bpf.h
-rw-r--r--    1 root  wheel    2024 Oct 18 04:45 pcap-namedb.h
-rw-r--r--    1 root  wheel    2226 Oct 18 04:45 pcap.h
drwxr-xr-x    7 root  wheel     224 Mar 13 19:03 pexpert
drwxr-xr-x    7 root  wheel     224 Sep  6  2019 php
-r--r--r--    1 root  wheel    1004 Oct  9 09:35 poll.h
-r--r--r--    1 root  wheel    1565 Aug 24  2019 printerdb.h
-r--r--r--    1 root  wheel   11130 Oct  9 09:35 printf.h
-rw-r--r--    1 root  wheel    6142 Aug 24  2019 profile.h
drwxr-xr-x    6 root  wheel     192 Mar 13 19:03 protocols
drwxr-xr-x   10 root  wheel     320 Mar 13 19:03 pthread
lrwxr-xr-x    1 root  wheel      17 Mar 13 19:03 pthread.h -> pthread/pthread.h
lrwxr-xr-x    1 root  wheel      22 Mar 13 19:03 pthread_impl.h -> pthread/pthread_impl.h
lrwxr-xr-x    1 root  wheel      22 Mar 13 19:03 pthread_spis.h -> pthread/pthread_spis.h
-r--r--r--    1 root  wheel    4749 Aug 24  2019 pwd.h
lrwxr-xr-x    1 root  wheel      79 Mar 13 19:03 python2.7 -> ../../System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7
-r--r--r--    1 root  wheel    4967 Oct  9 09:35 ranlib.h
drwxr-xr-x    4 root  wheel     128 Mar 13 19:04 readline
-r--r--r--    1 root  wheel    1664 Oct  9 09:35 readpassphrase.h
-r--r--r--    1 root  wheel    9422 Oct  9 09:35 regex.h
-rw-r--r--    1 root  wheel    2138 Aug 24  2019 removefile.h
-rw-r--r--    1 root  wheel   18854 Sep 25  2019 resolv.h
drwxr-xr-x   14 root  wheel     448 Mar 13 19:03 rpc
drwxr-xr-x   34 root  wheel    1088 Mar 13 19:03 rpcsvc
-r--r--r--    1 root  wheel    3738 Oct  9 09:35 rune.h
-r--r--r--    1 root  wheel    4198 Oct  9 09:35 runetype.h
-rw-r--r--    1 root  wheel    3517 Nov  7 22:47 sandbox.h
drwxr-xr-x   10 root  wheel     320 Mar 13 19:03 sasl
lrwxr-xr-x    1 root  wheel      15 Mar 13 19:03 sched.h -> pthread/sched.h
-r--r--r--    1 root  wheel    1373 Oct  9 09:35 search.h
drwxr-xr-x    6 root  wheel     192 Mar 13 19:03 secure
drwxr-xr-x   10 root  wheel     320 Mar 13 19:03 security
-r--r--r--    1 root  wheel    1135 Oct  9 09:35 semaphore.h
drwxr-xr-x    9 root  wheel     288 Mar 13 19:04 servers
-rw-r--r--    1 root  wheel    3139 Aug 24  2019 setjmp.h
-r--r--r--    1 root  wheel    2213 Oct  9 09:35 sgtty.h
-r--r--r--    1 root  wheel    5442 Oct  9 09:35 signal.h
drwxr-xr-x   19 root  wheel     608 Mar 13 19:03 simd
-rw-r--r--    1 root  wheel   38247 Aug 24  2019 slapi-plugin.h
-rw-r--r--    1 root  wheel    6969 Oct 10 11:00 spawn.h
-rw-r--r--    1 root  wheel  452133 Oct  2  2019 sqlite3.h
-rw-r--r--    1 root  wheel   33981 Oct  2  2019 sqlite3ext.h
-r--r--r--    1 root  wheel    3273 Oct  9 09:35 stab.h
-r--r--r--    1 root  wheel    1234 Oct  9 09:35 standards.h
-r--r--r--    1 root  wheel    3816 Oct  9 09:35 stddef.h
-r--r--r--    1 root  wheel    5556 Oct  9 09:35 stdint.h
-r--r--r--    1 root  wheel   16210 Oct  9 09:35 stdio.h
-r--r--r--    1 root  wheel   14558 Oct  9 09:35 stdlib.h
-r--r--r--    1 root  wheel    1968 Oct  9 09:35 strhash.h
-r--r--r--    1 root  wheel    7607 Oct  9 09:35 string.h
-r--r--r--    1 root  wheel    2233 Oct  9 09:35 stringlist.h
-r--r--r--    1 root  wheel    4208 Oct  9 09:35 strings.h
-r--r--r--    1 root  wheel    3041 Oct  9 09:35 struct.h
drwxr-xr-x  136 root  wheel    4352 Mar 13 19:03 sys
-rw-r--r--    1 root  wheel    5530 Aug 24  2019 sysdir.h
-r--r--r--    1 root  wheel    5472 Oct  9 09:35 sysexits.h
-r--r--r--    1 root  wheel    1004 Oct  9 09:35 syslog.h
-r--r--r--    1 root  wheel    3146 Oct  9 09:35 tar.h
lrwxr-xr-x    1 root  wheel      72 Mar 13 19:03 tcl.h -> ../../System/Library/Frameworks/Tcl.framework/Versions/8.5/Headers/tcl.h
lrwxr-xr-x    1 root  wheel      77 Mar 13 19:03 tclDecls.h -> ../../System/Library/Frameworks/Tcl.framework/Versions/8.5/Headers/tclDecls.h
lrwxr-xr-x    1 root  wheel      81 Mar 13 19:03 tclPlatDecls.h -> ../../System/Library/Frameworks/Tcl.framework/Versions/8.5/Headers/tclPlatDecls.h
lrwxr-xr-x    1 root  wheel      79 Mar 13 19:03 tclTomMath.h -> ../../System/Library/Frameworks/Tcl.framework/Versions/8.5/Headers/tclTomMath.h
lrwxr-xr-x    1 root  wheel      84 Mar 13 19:03 tclTomMathDecls.h -> ../../System/Library/Frameworks/Tcl.framework/Versions/8.5/Headers/tclTomMathDecls.h
-rw-r--r--    1 root  wheel   38205 Aug 24  2019 term.h
-rw-r--r--    1 root  wheel    7081 Aug 24  2019 term_entry.h
-rw-r--r--    1 root  wheel    3476 Aug 24  2019 termcap.h
-r--r--r--    1 root  wheel    1199 Oct  9 09:35 termios.h
-rw-r--r--    1 root  wheel   30569 Aug 24  2019 tgmath.h
-rw-r--r--    1 root  wheel   12206 Aug 24  2019 tic.h
drwxr-xr-x    7 root  wheel     224 Mar 13 19:03 tidy
-r--r--r--    1 root  wheel    8104 Oct  9 09:35 time.h
-r--r--r--    1 root  wheel    2684 Oct  9 09:35 timeconv.h
lrwxr-xr-x    1 root  wheel      70 Mar 13 19:03 tk.h -> ../../System/Library/Frameworks/Tk.framework/Versions/8.5/Headers/tk.h
lrwxr-xr-x    1 root  wheel      75 Mar 13 19:03 tkDecls.h -> ../../System/Library/Frameworks/Tk.framework/Versions/8.5/Headers/tkDecls.h
lrwxr-xr-x    1 root  wheel      82 Mar 13 19:03 tkIntXlibDecls.h -> ../../System/Library/Frameworks/Tk.framework/Versions/8.5/Headers/tkIntXlibDecls.h
lrwxr-xr-x    1 root  wheel      76 Mar 13 19:03 tkMacOSX.h -> ../../System/Library/Frameworks/Tk.framework/Versions/8.5/Headers/tkMacOSX.h
lrwxr-xr-x    1 root  wheel      79 Mar 13 19:03 tkPlatDecls.h -> ../../System/Library/Frameworks/Tk.framework/Versions/8.5/Headers/tkPlatDecls.h
-r--r--r--    1 root  wheel    2903 Oct  9 09:35 ttyent.h
-r--r--r--    1 root  wheel    5575 Oct  9 09:35 tzfile.h
-rw-r--r--    1 root  wheel    2054 Aug 24  2019 ucontext.h
-r--r--r--    1 root  wheel    1625 Oct  9 09:35 ulimit.h
-rw-r--r--    1 root  wheel    3005 Aug 24  2019 unctrl.h
-r--r--r--    1 root  wheel   28863 Oct  9 09:35 unistd.h
-rw-r--r--    1 root  wheel    8675 Aug 24  2019 unwind.h
-r--r--r--    1 root  wheel    4552 Oct  9 09:35 util.h
-r--r--r--    1 root  wheel    3164 Oct  9 09:35 utime.h
-r--r--r--    1 root  wheel    4010 Oct  9 09:35 utmp.h
-r--r--r--    1 root  wheel    6798 Oct  9 09:35 utmpx.h
drwxr-xr-x    3 root  wheel      96 Mar 13 19:03 uuid
drwxr-xr-x    3 root  wheel      96 Mar 13 19:03 vfs
-r--r--r--    1 root  wheel    5278 Oct  9 09:35 vis.h
drwxr-xr-x    3 root  wheel      96 Mar 13 19:03 voucher
-rw-r--r--    1 root  wheel    1420 Sep 27  2019 vproc.h
-r--r--r--    1 root  wheel   10206 Oct  9 09:35 wchar.h
-r--r--r--    1 root  wheel    3464 Oct  9 09:35 wctype.h
-r--r--r--    1 root  wheel    3085 Oct  9 09:35 wordexp.h
drwxr-xr-x    3 root  wheel      96 Mar 13 19:03 xar
-rw-r--r--    1 root  wheel    5976 Aug 24  2019 xattr_flags.h
-rw-r--r--    1 root  wheel    2669 Oct 24 01:35 xcselect.h
drwxr-xr-x   14 root  wheel     448 Mar 13 19:03 xlocale
-r--r--r--    1 root  wheel    3087 Oct  9 09:35 xlocale.h
drwxr-xr-x   11 root  wheel     352 Mar 13 19:03 xpc
-rw-r--r--    1 root  wheel   16085 Aug 24  2019 zconf.h
-rw-r--r--    1 root  wheel   98288 Aug 24  2019 zlib.h
```

**Comment by JCMais** [comment]
@shirshak55 try passing the following env var before the install command:
```shell
npm_config_curl_include_dirs="$(xcrun --show-sdk-path)/usr/include/"
```

example:
```shell
npm_config_curl_include_dirs="$(xcrun --show-sdk-path)/usr/include/" yarn add node-libcurl
```

**Comment by JCMais** [comment]
Btw, I was finally able to upgrade my macOs to Catalina, looks like passing `npm_config_curl_include_dirs` fixes the issue per above.

**Comment by JCMais** [comment]
I'm closing this as [v2.1.0](https://github.com/JCMais/node-libcurl/releases/tag/v2.1.0) (see the release page for full changelog) has been finally released. 🎉

If this is still an issue please re-open the issue.
