### ISSUE TITLE
Can not build for Node.js v14

### ISSUE THREAD

**Issue by eAmin** [JCMais/node-libcurl#215]
Build failure on node.js v14  both Ubuntu 18.04 and Windows 10 both failed:

log:
```
error /home/eamin/pedpo-chat/node_modules/node-libcurl: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: /home/eamin/pedpo-chat/node_modules/node-libcurl
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.14.0
node-pre-gyp info using node@14.0.0 | linux | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "/home/eamin/pedpo-chat/node_modules/node-libcurl/lib/binding/node_libcurl.node" (not found)
node-pre-gyp http GET https://github.com/JCMais/node-libcurl/releases/download/v2.1.0/node_libcurl-v2.1.0-node-v83-linux-x64-glibc.tar.gz
node-pre-gyp http 404 https://github.com/JCMais/node-libcurl/releases/download/v2.1.0/node_libcurl-v2.1.0-node-v83-linux-x64-glibc.tar.gz
node-pre-gyp WARN Tried to download(404): https://github.com/JCMais/node-libcurl/releases/download/v2.1.0/node_libcurl-v2.1.0-node-v83-linux-x64-glibc.tar.gz
node-pre-gyp WARN Pre-built binaries not found for node-libcurl@2.1.0 and node@14.0.0 (node-v83 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://github.com/JCMais/node-libcurl/releases/download/v2.1.0/node_libcurl-v2.1.0-node-v83-linux-x64-glibc.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.0.0 | linux | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.0.0 | linux | x64
gyp info find Python using Python version 2.7.17 found at "/usr/bin/python"
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/home/eamin/pedpo-chat/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/eamin/pedpo-chat/node_modules/node-libcurl/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/eamin/pedpo-chat/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/eamin/.cache/node-gyp/14.0.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/eamin/.cache/node-gyp/14.0.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/eamin/pedpo-chat/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/eamin/.cache/node-gyp/14.0.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/eamin/pedpo-chat/node_modules/node-libcurl',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Could not run curl-config, please make sure libcurl dev package is installed.
Output: /bin/sh: 1: curl-config: not found

gyp: Call to 'node /home/eamin/pedpo-chat/node_modules/node-libcurl/tools/curl-config.js --prefix' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/eamin/pedpo-chat/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 4.4.0-18362-Microsoft
gyp ERR! command "/usr/bin/node" "/home/eamin/pedpo-chat/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/eamin/pedpo-chat/node_modules/node-libcurl/lib/binding/node_libcurl.node" "--module_name=node_libcurl" "--module_path=/home/eamin/pedpo-chat/node_modules/node-libcurl/lib/binding" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd /home/eamin/pedpo-chat/node_modules/node-libcurl
gyp ERR! node -v v14.0.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /home/eamin/pedpo-chat/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/eamin/pedpo-chat/node_modules/node-libcurl/lib/binding/node_libcurl.node --module_name=node_libcurl --module_path=/home/eamin/pedpo-chat/node_modules/node-libcurl/lib/binding --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/eamin/pedpo-chat/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1051:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
node-pre-gyp ERR! System Linux 4.4.0-18362-Microsoft
node-pre-gyp ERR! command "/usr/bin/node" "/home/eamin/pedpo-chat/node_modules/node-libcurl/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/eamin/pedpo-chat/node_modules/node-libcurl
node-pre-gyp ERR! node -v v14.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.14.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /home/eamin/pedpo-chat/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/eamin/pedpo-chat/node_modules/node-libcurl/lib/binding/node_libcurl.node --module_name=node_libcurl --module_path=/home/eamin/pedpo-chat/node_modules/node-libcurl/lib/binding --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
```

**Comment by JCMais** [comment]
Here is the error:
> Could not run curl-config, please make sure libcurl dev package is installed.
> Output: /bin/sh: 1: curl-config: not found

Check the README about building from source: https://github.com/JCMais/node-libcurl#building-on-linux

**Comment by eAmin** [comment]
Thank you, it worked.

**Comment by nicoburns** [comment]
Are there plans for a release with prebuilt binaries for Node 14?

**Comment by JCMais** [comment]
@nicoburns working on it ;)

**Comment by JCMais** [comment]
@nicoburns there are prebuilt binaries for Node.js 14 now.

**Comment by nicoburns** [comment]
@JCMais Perfect. Thank you for the quick turnaround on this! Our backend services are now all updated to Node 14 :)
