### ISSUE TITLE
Node 14 support

### ISSUE THREAD

**Issue by ronag** [JCMais/node-libcurl#228]
Doesn't seem to be possible to install with Node 14.

```bash
error node_modules/node-libcurl: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: node_modules/node-libcurl
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.13.0
node-pre-gyp info using node@14.4.0 | darwin | x64
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp info check checked for "node_modules/node-libcurl/lib/binding/node_libcurl.node" (not found)
node-pre-gyp http GET https://github.com/JCMais/node-libcurl/releases/download/v2.0.3/node_libcurl-v2.0.3-node-v83-darwin-x64-unknown.tar.gz
node-pre-gyp http 404 https://github.com/JCMais/node-libcurl/releases/download/v2.0.3/node_libcurl-v2.0.3-node-v83-darwin-x64-unknown.tar.gz
node-pre-gyp WARN Tried to download(404): https://github.com/JCMais/node-libcurl/releases/download/v2.0.3/node_libcurl-v2.0.3-node-v83-darwin-x64-unknown.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for node-libcurl@2.0.3 and node@14.4.0 (node-v83 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/JCMais/node-libcurl/releases/download/v2.0.3/node_libcurl-v2.0.3-node-v83-darwin-x64-unknown.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@14.4.0 | darwin | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@14.4.0 | darwin | x64
gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [
gyp info spawn args   'node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   'node_modules/node-libcurl/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/ronagy/Library/Caches/node-gyp/14.4.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/ronagy/Library/Caches/node-gyp/14.4.0',
gyp info spawn args   '-Dnode_gyp_dir=node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/ronagy/Library/Caches/node-gyp/14.4.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=node_modules/node-libcurl',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.3
gyp info using node@14.4.0 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/node_libcurl/src/node_libcurl.o
clang: error: no such file or directory: '/usr/include'
make: *** [Release/obj.target/node_libcurl/src/node_libcurl.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 19.4.0
gyp ERR! command "/Users/ronagy/.nvm/versions/node/v14.4.0/bin/node" "node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=node_modules/node-libcurl/lib/binding/node_libcurl.node" "--module_name=node_libcurl" "--module_path=node_modules/node-libcurl/lib/binding" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
gyp ERR! cwd node_modules/node-libcurl
gyp ERR! node -v v14.4.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/ronagy/.nvm/versions/node/v14.4.0/bin/node node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=node_modules/node-libcurl/lib/binding/node_libcurl.node --module_name=node_libcurl --module_path=node_modules/node-libcurl/lib/binding --napi_version=6 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1051:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
node-pre-gyp ERR! System Darwin 19.4.0
node-pre-gyp ERR! command "/Users/ronagy/.nvm/versions/node/v14.4.0/bin/node" "node_modules/node-libcurl/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd node_modules/node-libcurl
node-pre-gyp ERR! node -v v14.4.0
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok 
Failed to execute '/Users/ronagy/.nvm/versions/node/v14.4.0/bin/node node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=node_modules/node-libcurl/lib/binding/node_libcurl.node --module_name=node
```

**Comment by JCMais** [comment]
2.0.3 has no prebuilt binaries for Node.js v14, so it will try to build from source.

The error you are getting:
```
  CXX(target) Release/obj.target/node_libcurl/src/node_libcurl.o
clang: error: no such file or directory: '/usr/include'
```
Is described on the README: https://github.com/JCMais/node-libcurl#building-on-macos
