### ISSUE TITLE
npm_config_runtime=electron npm_config_target=$(yarn --silent electron --version) npm_config_disturl=https://www.electronjs.org/headers yarn add node-libcurl  Failed

### ISSUE THREAD

**Issue by im-sunil** [JCMais/node-libcurl#234]
error /Users/sunilbagde/code/my-app-e/node_modules/node-libcurl: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: /Users/sunilbagde/code/my-app-e/node_modules/node-libcurl
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.14.0
node-pre-gyp info using node@10.16.0 | darwin | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "/Users/sunilbagde/code/my-app-e/node_modules/node-libcurl/lib/binding/node_libcurl.node" (not found)
node-pre-gyp http GET https://github.com/JCMais/node-libcurl/releases/download/v2.1.3/node_libcurl-v2.1.3-electron-v9.0-darwin-x64-unknown.tar.gz
node-pre-gyp http 404 https://github.com/JCMais/node-libcurl/releases/download/v2.1.3/node_libcurl-v2.1.3-electron-v9.0-darwin-x64-unknown.tar.gz
node-pre-gyp WARN Tried to download(404): https://github.com/JCMais/node-libcurl/releases/download/v2.1.3/node_libcurl-v2.1.3-electron-v9.0-darwin-x64-unknown.tar.gz
node-pre-gyp WARN Pre-built binaries not found for node-libcurl@2.1.3 and electron@v9.0.5 (electron-v9.0 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://github.com/JCMais/node-libcurl/releases/download/v2.1.3/node_libcurl-v2.1.3-electron-v9.0-darwin-x64-unknown.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@10.16.0 | darwin | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@10.16.0 | darwin | x64
gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
gyp http GET https://www.electronjs.org/headers/v9.0.5/node-v9.0.5-headers.tar.gz
gyp http 200 https://www.electronjs.org/headers/v9.0.5/node-v9.0.5-headers.tar.gz
gyp http GET https://www.electronjs.org/headers/v9.0.5/SHASUMS256.txt
gyp http 200 https://www.electronjs.org/headers/v9.0.5/SHASUMS256.txt
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [ '/Users/sunilbagde/code/my-app-e/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/sunilbagde/code/my-app-e/node_modules/node-libcurl/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/sunilbagde/code/my-app-e/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/sunilbagde/Library/Caches/node-gyp/9.0.5/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/sunilbagde/Library/Caches/node-gyp/9.0.5',
gyp info spawn args   '-Dnode_gyp_dir=/Users/sunilbagde/code/my-app-e/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/sunilbagde/Library/Caches/node-gyp/9.0.5/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/sunilbagde/code/my-app-e/node_modules/node-libcurl',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@10.16.0 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/node_libcurl/src/node_libcurl.o
clang: error: no such file or directory: '/usr/include'
make: *** [Release/obj.target/node_libcurl/src/node_libcurl.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/sunilbagde/code/my-app-e/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 19.2.0
gyp ERR! command "/usr/local/bin/node" "/Users/sunilbagde/code/my-app-e/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/sunilbagde/code/my-app-e/node_modules/node-libcurl/lib/binding/node_libcurl.node" "--module_name=node_libcurl" "--module_path=/Users/sunilbagde/code/my-app-e/node_modules/node-libcurl/lib/binding" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v9.0"
gyp ERR! cwd /Users/sunilbagde/code/my-app-e/node_modules/node-libcurl
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /Users/sunilbagde/code/my-app-e/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/sunilbagde/code/my-app-e/node_modules/node-libcurl/lib/binding/node_libcurl.node --module_name=node_libcurl --module_path=/Users/sunilbagde/code/my-app-e/node_modules/node-libcurl/lib/binding --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v9.0' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/sunilbagde/code/my-app-e/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Darwin 19.2.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/sunilbagde/code/my-app-e/node_modules/node-libcurl/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/sunilbagde/code/my-app-e/node_modules/node-libcurl
node-pre-gyp ERR! node -v v10.16.0
node-pre-gyp ERR! node-pre-gyp -v v0.14.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /Users/sunilbagde/code/my-app-e/node_modules/node-gyp/bin/node-gyp.js build --fal

➜  my-app-e git:(master) ✗ npm_config_runtime=electron npm_config_target=$(yarn --silent electron --version) npm_config_disturl=https://www.electronjs.org/headers yarn add node-libcurl
yarn add v1.22.4
[1/4] 🔍  Resolving packages...
warning hawk@6.0.2: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
warning hawk > sntp@2.1.0: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
warning hawk > cryptiles@3.1.4: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning hawk > boom@4.3.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning hawk > cryptiles > boom@5.2.0: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning hawk > hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning hawk > sntp > hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning hawk > boom > hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning hawk > cryptiles > boom > hoek@4.2.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
warning httpsnippet > fs-writefile-promise > mkdirp-promise@1.1.0: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.
warning insomnia-libcurl > inlc > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning jsonlint > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > insomnia-components@2.2.12" has unmet peer dependency "react@^16.8.6".
warning " > insomnia-components@2.2.12" has unmet peer dependency "react-dom@^16.8.6".
warning "insomnia-components > react-switch@5.0.1" has unmet peer dependency "react@^15.3.0 || ^16.0.0".
warning "insomnia-components > react-switch@5.0.1" has unmet peer dependency "react-dom@^15.3.0 || ^16.0.0".
warning "insomnia-components > framer-motion@1.11.1" has unmet peer dependency "react@^16.8".
warning "insomnia-components > framer-motion@1.11.1" has unmet peer dependency "react-dom@^16.8".
warning "insomnia-components > styled-components@4.4.1" has unmet peer dependency "react@>= 16.3.0".
warning "insomnia-components > styled-components@4.4.1" has unmet peer dependency "react-dom@>= 16.3.0".
[4/4] 🔨  Building fresh packages...
[1/8] ⠈ font-scanner
[8/8] ⠈ node-libcurl
[3/8] ⠈ inlc
[7/8] ⠈ electron
error /Users/sunilbagde/code/my-app-e/node_modules/node-libcurl: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: /Users/sunilbagde/code/my-app-e/node_modules/node-libcurl
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.14.0
node-pre-gyp info using node@10.16.0 | darwin | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "/Users/sunilbagde/code/my-app-e/node_modules/node-libcurl/lib/binding/node_libcurl.node" (not found)
node-pre-gyp http GET https://github.com/JCMais/node-libcurl/releases/download/v2.1.3/node_libcurl-v2.1.3-electron-v9.0-darwin-x64-unknown.tar.gz
node-pre-gyp http 404 https://github.com/JCMais/node-libcurl/releases/download/v2.1.3/node_libcurl-v2.1.3-electron-v9.0-darwin-x64-unknown.tar.gz
node-pre-gyp WARN Tried to download(404): https://github.com/JCMais/node-libcurl/releases/download/v2.1.3/node_libcurl-v2.1.3-electron-v9.0-darwin-x64-unknown.tar.gz
node-pre-gyp WARN Pre-built binaries not found for node-libcurl@2.1.3 and electron@v9.0.5 (electron-v9.0 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://github.com/JCMais/node-libcurl/releases/download/v2.1.3/node_libcurl-v2.1.3-electron-v9.0-darwin-x64-unknown.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@10.16.0 | darwin | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@10.16.0 | darwin | x64
gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
gyp info spawn args [ '/Users/sunilbagde/code/my-app-e/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/sunilbagde/code/my-app-e/node_modules/node-libcurl/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/sunilbagde/code/my-app-e/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/sunilbagde/Library/Caches/node-gyp/9.0.5/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/sunilbagde/Library/Caches/node-gyp/9.0.5',
gyp info spawn args   '-Dnode_gyp_dir=/Users/sunilbagde/code/my-app-e/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/sunilbagde/Library/Caches/node-gyp/9.0.5/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/sunilbagde/code/my-app-e/node_modules/node-libcurl',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@10.16.0 | darwin | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/node_libcurl/src/node_libcurl.o
clang: error: no such file or directory: '/usr/include'
make: *** [Release/obj.target/node_libcurl/src/node_libcurl.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/sunilbagde/code/my-app-e/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 19.2.0
gyp ERR! command "/usr/local/bin/node" "/Users/sunilbagde/code/my-app-e/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/sunilbagde/code/my-app-e/node_modules/node-libcurl/lib/binding/node_libcurl.node" "--module_name=node_libcurl" "--module_path=/Users/sunilbagde/code/my-app-e/node_modules/node-libcurl/lib/binding" "--napi_version=4" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v9.0"
gyp ERR! cwd /Users/sunilbagde/code/my-app-e/node_modules/node-libcurl
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /Users/sunilbagde/code/my-app-e/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/sunilbagde/code/my-app-e/node_modules/node-libcurl/lib/binding/node_libcurl.node --module_name=node_libcurl --module_path=/Users/sunilbagde/code/my-app-e/node_modules/node-libcurl/lib/binding --napi_version=4 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v9.0' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/sunilbagde/code/my-app-e/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Darwin 19.2.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/sunilbagde/code/my-app-e/node_modules/node-libcurl/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/sunilbagde/code/my-app-e/node_modules/node-libcurl
node-pre-gyp ERR! node -v v10.16.0
node-pre-gyp ERR! node-pre-gyp -v v0.14.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /Users/sunilbagde/code/my-app-e/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --mod

**Comment by im-sunil** [comment]
Fixed
