### ISSUE TITLE
Unable to run on node v13.12.0 and v14.11.0

### ISSUE THREAD

**Issue by keirankozlowski** [JCMais/node-libcurl#250]
Installed the package and attempted to start, giving me a "module not found" error. See below: 

```npm run start

> @tnt/livevox-api@1.2.0 start /Users/keirankozlowski/Documents/work/tnt-livevox-api
> node dist/index.js

webpack:///./src/services/helper.service.ts?:51
var Curl = __webpack_require__(!(function webpackMissingModule() { var e = new Error("Cannot find module 'node-libcurl'"); e.code = 'MODULE_NOT_FOUND'; throw e; }())).Curl;
                                ^

Error: Cannot find module 'node-libcurl'
    at webpackMissingModule (webpack:///./src/services/helper.service.ts?:51:76)
    at Object.eval (webpack:///./src/services/helper.service.ts?:51:163)
    at eval (webpack:///./src/services/helper.service.ts?:386:30)
    at Object../src/services/helper.service.ts (/Users/keirankozlowski/Documents/work/tnt-livevox-api/dist/index.js:921:1)
    at __webpack_require__ (/Users/keirankozlowski/Documents/work/tnt-livevox-api/dist/index.js:749:30)
    at fn (/Users/keirankozlowski/Documents/work/tnt-livevox-api/dist/index.js:60:20)
    at eval (webpack:///./src/routes/contact.route.ts?:44:24)
    at Object../src/routes/contact.route.ts (/Users/keirankozlowski/Documents/work/tnt-livevox-api/dist/index.js:885:1)
    at __webpack_require__ (/Users/keirankozlowski/Documents/work/tnt-livevox-api/dist/index.js:749:30)
    at fn (/Users/keirankozlowski/Documents/work/tnt-livevox-api/dist/index.js:60:20) {
  code: 'MODULE_NOT_FOUND'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @tnt/livevox-api@1.2.0 start: `node dist/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @tnt/livevox-api@1.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.```

**Comment by JCMais** [comment]
Hi @keirankozlowski , do you have some steps I can try to reproduce the issue?
I see you are using webpack, did you install the [`node-loader`](https://github.com/webpack-contrib/node-loader)?

**Comment by JCMais** [comment]
Closing due to inactivity, if you have some code that is able to reproduce this, feel free to reopen the issue.

**Comment by allang** [comment]
Experiencing this as well. 

```
➜  folks git:(98-slack-auth) ✗ npm i node-libcurl --save

npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-pre-gyp@0.15.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm ERR! code 1
npm ERR! path /Users/allangrinshtein/Documents/workspace/folks/node_modules/node-libcurl
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! Failed to execute '/usr/local/Cellar/node/15.8.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/allangrinshtein/Documents/workspace/folks/node_modules/node-libcurl/lib/binding/node_libcurl.node --module_name=node_libcurl --module_path=/Users/allangrinshtein/Documents/workspace/folks/node_modules/node-libcurl/lib/binding --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v88' (1)

...

```

Was there a breaking change recently? Unable to do a basic install.
