### ISSUE TITLE
Breaking change on v2.3.1 ? 

### ISSUE THREAD

**Issue by ddolcimascolo** [JCMais/node-libcurl#278]
Hi @JCMais

Our build fails with v2.3.1, see the trace below.

```
$ npm ci
> node-libcurl@2.3.1 install /builds/stordata/collectors/node_modules/node-libcurl
> node-pre-gyp install --fallback-to-build
node-pre-gyp WARN Using request for node-pre-gyp https download 
[node-libcurl] Success: "/builds/stordata/collectors/node_modules/node-libcurl/lib/binding/node_libcurl.node" is installed via remote
> node-libcurl@2.3.1 postinstall /builds/stordata/collectors/node_modules/node-libcurl
> node scripts/postinstall
node-libcurl WARN Could not finish postinstall 
node-libcurl ERR! the latest libstdc++ is missing on your system! 
node-libcurl ERR! On Ubuntu you can install it using: 
node-libcurl ERR! $ sudo add-apt-repository ppa:ubuntu-toolchain-r/test 
node-libcurl ERR! $ sudo apt-get update 
node-libcurl ERR! $ sudo apt-get install libstdc++-4.9-dev 
> @stordata/supersecret@1.0.2 install /builds/stordata/collectors/node_modules/@stordata/supersecret
> node-gyp rebuild
make: Entering directory '/builds/stordata/collectors/node_modules/@stordata/supersecret/build'
  CXX(target) Release/obj.target/supersecret/src/supersecret.o
  SOLINK_MODULE(target) Release/obj.target/supersecret.node
  COPY Release/supersecret.node
make: Leaving directory '/builds/stordata/collectors/node_modules/@stordata/supersecret/build'
added 713 packages in 19.281s
$ grunt
Running "env:tests" (env) task
Running "eslint:target" (eslint) task
Running "simplemocha:unit" (simplemocha) task
Warning: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /builds/stordata/collectors/node_modules/node-libcurl/lib/binding/node_libcurl.node) Use --force to continue.
Aborted due to warnings.
```

My understanding is that you require a new minimum version of `libstdc++` to build the lib from source, not to _run_ it, right? That would be a major breaking change I suppose... 

Thanks for your help! 

Regards, 
David

**Comment by JCMais** [comment]
Investigating this, thanks for reporting.

**Comment by JCMais** [comment]
@ddolcimascolo @david8388 could you please try to install the new version again? I have updated the prebuilt binaries.

The issue was caused in the migration of the build process from TravisCI to GitHub Actions.

In TravisCI (versions <= 2.3.1) the addon was being built using Ubuntu 18.04, but when I migrated to GitHub Actions I used Ubuntu 20.04. I have fixed it by downgrading the Ubuntu version being used to run the build-and-release workflow.

**Comment by ddolcimascolo** [comment]
Thx @JCMais Simply retrying the build worked. I think you can close if @david8388 aggrees too.

Cheers,
David

**Comment by ddolcimascolo** [comment]
Hi again @JCMais 

I talked a little bit too fast, a part of the build still fails, but the error wasn't raised during the build I don't know why. Deploying to DEV env made things break :/

The trace is 
```
> node-libcurl@2.3.1 install /builds/stordata/collectors/node_modules/node-libcurl
> node-pre-gyp install --fallback-to-build
node-pre-gyp WARN Using request for node-pre-gyp https download 
[node-libcurl] Success: "/builds/stordata/collectors/node_modules/node-libcurl/lib/binding/node_libcurl.node" is installed via remote
> node-libcurl@2.3.1 postinstall /builds/stordata/collectors/node_modules/node-libcurl
> node scripts/postinstall
node-libcurl WARN Could not finish postinstall 
node-libcurl ERR! Error: Command failed: node "/builds/stordata/collectors/node_modules/node-libcurl/dist/index.js"
internal/modules/cjs/loader.js:1122
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /builds/stordata/collectors/node_modules/node-libcurl/lib/binding/node_libcurl.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/builds/stordata/collectors/node_modules/node-libcurl/dist/Easy.js:5:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
```

The specificity here is that it's Debian Stretch (9). I know it's old but previous version worked like a charm.

Anything you can do on your side ? If not, meaning you can't support Debian 9 anymore, would you consider release a major version then? It's bad to break a production app on a patch release :)

Thanks in advance,
David

**Comment by JCMais** [comment]
@ddolcimascolo having this breaking change is not something that was planned for this release, sorry for that. Turns out that the version being used in TravisCI was in fact Ubuntu 14, I will try to run the build on Ubuntu 16 and see if the glibc version is lower than 2.25.

I should be able to do that in 3~4 hours.

**Comment by JCMais** [comment]
@ddolcimascolo let me know if it works for you now.

I just tested it with the following docker image and it worked:

```
from node:14-stretch

WORKDIR /app

RUN yarn add node-libcurl
RUN node -e "console.log(require('node-libcurl').Curl.getVersionInfoString())"

ENTRYPOINT /bin/bash
```

**Comment by david8388** [comment]
@JCMais, Thank you so much for resolving this issue.

Looks good on my machine

**Comment by ddolcimascolo** [comment]
OK on my side now @JCMais

Thx a lot for your help, and for thuis great lib

Cheers,
David

**Comment by staa99-mono** [comment]
Hi @JCMais,
Version 3.0.0 is broken in a similar way.

Using the dockerfile below doesn't work
```Dockerfile
FROM node:16

WORKDIR /app

RUN npm i node-libcurl     # it works when this is replaced with node-libcurl@^2
RUN node -e "console.log(require('node-libcurl').Curl.getVersionInfoString())"

ENTRYPOINT /bin/bash
```

**Comment by saviomd** [comment]
I'm having issues related to this with 3.0.0 as well.
The app works as it should locally but gives an internal error when running on gcloud.
Application Errors on app engine console:
```
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /workspace/node_modules/node-libcurl/lib/binding/node_libcurl.node) at Object.Module._extensions..node (node:internal/modules/cjs/loader:1275:18)
```
(reverting to 2.3.4 fixed it)
