### ISSUE TITLE
npm -S i node-libcurl >> response status 503 Service Unavailable on /releases/download/v2.3.4/node_libcurl-v2.3.4-node-v108-linux-x64-glibc.tar.gz

### ISSUE THREAD

**Issue by Marty-Stu** [JCMais/node-libcurl#361]
**Describe the bug**

During the installation of the module, an attempt is made to download a file that does not exist (`node_libcurl-v2.3.4-node-v108-linux-x64-glibc.tar.gz`).

**To Reproduce**

1. `npm -S i node-libcurl`
2. file not found
    `response status 503 Service Unavailable`
    for file
    `https://github.com/JCMais/node-libcurl/releases/download/v2.3.4/node_libcurl-v2.3.4-node-v108-linux-x64-glibc.tar.gz`
3. stdout:
```
658 error code 1
659 error path /home/ti/nodejs/tests/000/node_modules/node-libcurl
660 error command failed
661 error command sh -c node-pre-gyp install --fallback-to-build
662 error Failed to execute '/home/ti/.nvm/versions/node/v18.5.0/bin/node /home/ti/.nvm/versions/node/v18.5.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/ti/nodejs/tests/000/node_modules/node-libcurl/lib/binding/node_libcurl.node --module_name=node_libcurl --module_path=/home/ti/nodejs/tests/000/node_modules/node-libcurl/lib/binding --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
663 error node-pre-gyp info it worked if it ends with ok
663 error node-pre-gyp info using node-pre-gyp@1.0.5
663 error node-pre-gyp info using node@18.5.0 | linux | x64
663 error node-pre-gyp info check checked for "/home/ti/nodejs/tests/000/node_modules/node-libcurl/lib/binding/node_libcurl.node" (not found)
663 error node-pre-gyp http GET https://github.com/JCMais/node-libcurl/releases/download/v2.3.4/node_libcurl-v2.3.4-node-v108-linux-x64-glibc.tar.gz
663 error node-pre-gyp ERR! install response status 404 Not Found on https://github.com/JCMais/node-libcurl/releases/download/v2.3.4/node_libcurl-v2.3.4-node-v108-linux-x64-glibc.tar.gz 
663 error node-pre-gyp WARN Pre-built binaries not installable for node-libcurl@2.3.4 and node@18.5.0 (node-v108 ABI, glibc) (falling back to source compile with node-gyp) 
663 error node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/JCMais/node-libcurl/releases/download/v2.3.4/node_libcurl-v2.3.4-node-v108-linux-x64-glibc.tar.gz 
663 error gyp info it worked if it ends with ok
663 error gyp info using node-gyp@9.0.0
663 error gyp info using node@18.5.0 | linux | x64
663 error gyp info ok 
663 error gyp info it worked if it ends with ok
663 error gyp info using node-gyp@9.0.0
663 error gyp info using node@18.5.0 | linux | x64
663 error gyp info find Python using Python version 3.9.2 found at "/usr/bin/python3"
663 error gyp info spawn /usr/bin/python3
663 error gyp info spawn args [
663 error gyp info spawn args   '/home/ti/.nvm/versions/node/v18.5.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
663 error gyp info spawn args   'binding.gyp',
663 error gyp info spawn args   '-f',
663 error gyp info spawn args   'make',
663 error gyp info spawn args   '-I',
663 error gyp info spawn args   '/home/ti/nodejs/tests/000/node_modules/node-libcurl/build/config.gypi',
663 error gyp info spawn args   '-I',
663 error gyp info spawn args   '/home/ti/.nvm/versions/node/v18.5.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
663 error gyp info spawn args   '-I',
663 error gyp info spawn args   '/home/ti/.cache/node-gyp/18.5.0/include/node/common.gypi',
663 error gyp info spawn args   '-Dlibrary=shared_library',
663 error gyp info spawn args   '-Dvisibility=default',
663 error gyp info spawn args   '-Dnode_root_dir=/home/ti/.cache/node-gyp/18.5.0',
663 error gyp info spawn args   '-Dnode_gyp_dir=/home/ti/.nvm/versions/node/v18.5.0/lib/node_modules/npm/node_modules/node-gyp',
663 error gyp info spawn args   '-Dnode_lib_file=/home/ti/.cache/node-gyp/18.5.0/<(target_arch)/node.lib',
663 error gyp info spawn args   '-Dmodule_root_dir=/home/ti/nodejs/tests/000/node_modules/node-libcurl',
663 error gyp info spawn args   '-Dnode_engine=v8',
663 error gyp info spawn args   '--depth=.',
663 error gyp info spawn args   '--no-parallel',
663 error gyp info spawn args   '--generator-output',
663 error gyp info spawn args   'build',
663 error gyp info spawn args   '-Goutput_dir=.'
663 error gyp info spawn args ]
663 error Could not run curl-config, please make sure libcurl dev package is installed.
663 error Output: /bin/sh: 1: curl-config: not found
663 error
663 error gyp: Call to 'node /home/ti/nodejs/tests/000/node_modules/node-libcurl/scripts/curl-config.js --prefix' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
663 error gyp ERR! configure error 
663 error gyp ERR! stack Error: `gyp` failed with exit code: 1
663 error gyp ERR! stack     at ChildProcess.onCpExit (/home/ti/.nvm/versions/node/v18.5.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:261:16)
663 error gyp ERR! stack     at ChildProcess.emit (node:events:537:28)
663 error gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
663 error gyp ERR! System Linux 5.10.102.1-microsoft-standard-WSL2
663 error gyp ERR! command "/home/ti/.nvm/versions/node/v18.5.0/bin/node" "/home/ti/.nvm/versions/node/v18.5.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/ti/nodejs/tests/000/node_modules/node-libcurl/lib/binding/node_libcurl.node" "--module_name=node_libcurl" "--module_path=/home/ti/nodejs/tests/000/node_modules/node-libcurl/lib/binding" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
663 error gyp ERR! cwd /home/ti/nodejs/tests/000/node_modules/node-libcurl
663 error gyp ERR! node -v v18.5.0
663 error gyp ERR! node-gyp -v v9.0.0
663 error gyp ERR! not ok 
663 error node-pre-gyp ERR! build error 
663 error node-pre-gyp ERR! stack Error: Failed to execute '/home/ti/.nvm/versions/node/v18.5.0/bin/node /home/ti/.nvm/versions/node/v18.5.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/ti/nodejs/tests/000/node_modules/node-libcurl/lib/binding/node_libcurl.node --module_name=node_libcurl --module_path=/home/ti/nodejs/tests/000/node_modules/node-libcurl/lib/binding --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
663 error node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/ti/nodejs/tests/000/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
663 error node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:537:28)
663 error node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
663 error node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
663 error node-pre-gyp ERR! System Linux 5.10.102.1-microsoft-standard-WSL2
663 error node-pre-gyp ERR! command "/home/ti/.nvm/versions/node/v18.5.0/bin/node" "/home/ti/nodejs/tests/000/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
663 error node-pre-gyp ERR! cwd /home/ti/nodejs/tests/000/node_modules/node-libcurl
663 error node-pre-gyp ERR! node -v v18.5.0
663 error node-pre-gyp ERR! node-pre-gyp -v v1.0.5
663 error node-pre-gyp ERR! not ok
664 verbose exit 1
665 timing npm Completed in 6646ms
666 verbose unfinished npm timer reify 1662306539261
667 verbose unfinished npm timer reify:build 1662306543865
668 verbose unfinished npm timer build 1662306543866
669 verbose unfinished npm timer build:deps 1662306543866
670 verbose unfinished npm timer build:run:install 1662306543896
671 verbose unfinished npm timer build:run:install:node_modules/node-libcurl 1662306543896
672 verbose code 1
673 error A complete log of this run can be found in:
673 error     /home/ti/.npm/_logs/2022-09-04T15_48_59_134Z-debug-0.log
```

**Version information:**

Version:
```
# uname -a
Linux L00--3720-32 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 GNU/Linux

# nvm --version
0.37.2

# npm --version
8.12.1

# node --version
v18.5.0

# python --version
Python 2.7.18

# python3 --version
Python 3.9.2
```

OS: Linux L00--3720-32 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 GNU/Linux
Node.js Version: v18.5.0

**Additional context**

**Comment by wherreral** [comment]
I got the same issue in a different setup

**Version information:**
Version:

`node --version
v18.14.0

npm --version
9.3.1

python3 --version
Python 3.8.10

uname -a
Linux Box 5.15.0-69-generic #76~20.04.1-Ubuntu SMP Mon Mar 20 15:54:19 UTC 2023 x86_64 x86_64 x86_64 `GNU/Linux`
`
