### ISSUE TITLE
Getting compatibility issue with libstdc++.so.6

### ISSUE THREAD

**Issue by webdevabhi** [JCMais/node-libcurl#385]
while deploying my app using docker to ubuntu server.
Getting error like:

````
This error message indicates that the version of libstdc++.so.6 installed on your system is too old to be compatible with the version of node-libcurl that you are trying to use. Specifically, the version of GLIBCXX required by node-libcurl is 3.4.26, which is not available on your system.

To resolve this issue, you can try one or more of the following solutions:

Upgrade your operating system to a version that includes the required GLIBCXX version.

Install a newer version of the libstdc++ library that includes the required GLIBCXX version.

Compile node-libcurl from source on your system, which will link against the version of libstdc++ that is installed on your system.

Use a precompiled binary of node-libcurl that is compatible with the version of libstdc++ installed on your system.

The best solution depends on your specific situation, and you may need to consult with a software developer or system administrator for further assistance.
````

**Comment by delebakare** [comment]
Getting similar error when deploying firebase functions using github actions. Here's the error.

Function failed on loading user code. This is likely due to a bug in the user code. Error message: Provided module can't be loaded.
Is there a syntax error in your code?
Detailed stack trace: Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /workspace/node_modules/node-libcurl/lib/binding/node_libcurl.node)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:11[44]
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/workspace/node_modules/node-libcurl/dist/Easy.js:5:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:9[50]
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
Could not load the function, shutting down.

**Comment by delebakare** [comment]
using v2.3.4 fixed it for me

**Comment by JCMais** [comment]
This error message means you have to build node-libcurl from source for your OS, instructions on how to do this are available in the README.
