### ISSUE TITLE
Error after upgrade to Node 20.10 ...: ERR_DLOPEN_FAILED

### ISSUE THREAD

**Issue by xstable** [JCMais/node-libcurl#402]
**Describe the bug**

I got following error after upgrading nodeJS to v20.10.0: 

```bash
2023-11-27T08:30:00: Node.js v20.10.0
2023-11-27T09:20:00: node:events:503
2023-11-27T09:20:00:     const err = new ERR_UNHANDLED_ERROR(stringifiedEr);
2023-11-27T09:20:00:                 ^
2023-11-27T09:20:00: 
2023-11-27T09:20:00: Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Command failed: cd ./serverScripts/wwoImporter/ && ./wwoImporter.cjs -env production\n' +
2023-11-27T09:20:00:   'node:internal/modules/cjs/loader:1473\n' +
2023-11-27T09:20:00:   '  return process.dlopen(module, path.toNamespacedPath(filename));\n' +
2023-11-27T09:20:00:   '                 ^\n' +
2023-11-27T09:20:00:   '\n' +
2023-11-27T09:20:00:   'Error: /home/deploy/backend_production/releases/2023-11-24-19-14-40-617-UTC/node_modules/node-libcurl/lib/binding/node_libcurl.node: undefined symbol: _ZN2v82V88MakeWeakEPmPvPFvRKNS_16WeakCallbackInfoIvEEENS_16WeakCallbackTypeE\n' +
2023-11-27T09:20:00:   '    at Module._extensions..node (node:internal/modules/cjs/loader:1473:18)\n' +
2023-11-27T09:20:00:   '    at Module.load (node:internal/modules/cjs/loader:1207:32)\n' +
2023-11-27T09:20:00:   '    at Module._load (node:internal/modules/cjs/loader:1023:12)\n' +
2023-11-27T09:20:00:   '    at Module.require (node:internal/modules/cjs/loader:1235:19)\n' +
2023-11-27T09:20:00:   '    at require (node:internal/modules/helpers:176:18)\n' +
2023-11-27T09:20:00:   '    at Object.<anonymous> (/home/deploy/backend_production/releases/2023-11-24-19-14-40-617-UTC/node_modules/node-libcurl/dist/Easy.js:5:18)\n' +
2023-11-27T09:20:00:   '    at Module._compile (node:internal/modules/cjs/loader:1376:14)\n' +
2023-11-27T09:20:00:   '    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)\n' +
2023-11-27T09:20:00:   '    at Module.load (node:internal/modules/cjs/loader:1207:32)\n' +
2023-11-27T09:20:00:   '    at Module._load (node:internal/modules/cjs/loader:1023:12) {\n' +
2023-11-27T09:20:00:   "  code: 'ERR_DLOPEN_FAILED'\n" +
2023-11-27T09:20:00:   '}\n' +
2023-11-27T09:20:00:   '\n' 
```
**To Reproduce**

Steps to reproduce the behavior, if possible, provide a Dockerfile that is able to reproduce the issue.

**Version information:**

Installed Packages: 
```json
"dependencies": {
    "add": "^2.0.6",
    "ajv": "^8.10.0",
    "ajv-draft-04": "^1.0.0",
    "ajv-errors": "^3.0.0",
    "axios": "^1.1.3",
    "basic-ftp": "^5.0.3",
    "bcrypt": "^5.0.1",
    "cheerio": "^1.0.0-rc.10",
    "dayjs": "^1.11.7",
    "esm": "^3.2.25",
    "express-useragent": "^1.0.15",
    "fast-xml-parser": "^4.0.2",
    "form-data": "^4.0.0",
    "fs-extra": "^11.1.0",
    "get-ssl-certificate": "^2.3.3",
    "html-to-text": "^9.0.5",
    "ipaddr.js": "^2.0.1",
    "lodash-es": "^4.17.21",
    "mjml": "^4.13.0",
    "mongo-dot-notation": "^3.1.0",
    "mongodb": "^6.3.0",
    "node-libcurl": "^3.0.0",
    "node-schedule": "^2.1.1",
    "nodemailer": "^6.6.3",
    "nodemon": "^3.0.1",
    "sheetjs-style": "^0.15.8",
    "uWebSockets.js": "uNetworking/uWebSockets.js#v20.34.0",
    "xlsx": "^0.18.5",
    "yarn": "^1.22.18"
  },
```
<!---
If the addon was installed, please run the following inside the directory you installed it:

```
node -e "console.log(require('node-libcurl').Curl.getVersionInfoString())"
node:internal/modules/cjs/loader:1473
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /home/deploy/backend_production/releases/2023-11-24-19-14-40-617-UTC/node_modules/node-libcurl/lib/binding/node_libcurl.node: undefined symbol: _ZN2v82V88MakeWeakEPmPvPFvRKNS_16WeakCallbackInfoIvEEENS_16WeakCallbackTypeE
    at Module._extensions..node (node:internal/modules/cjs/loader:1473:18)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/home/deploy/backend_production/releases/2023-11-24-19-14-40-617-UTC/node_modules/node-libcurl/dist/Easy.js:5:18)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v20.10.0
```

OS:
Node.js Version: 20.10.0

**Comment by xstable** [comment]
If I fully remove `node_modules` and try to install it again, I got  some errors like: 
```
error /home/deploy/backend_staging/releases/2023-11-24-19-15-16-716-UTC/node_modules/node-libcurl: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /home/deploy/backend_staging/releases/2023-11-24-19-15-16-716-UTC/node_modules/node-libcurl
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.10
node-pre-gyp info using node@20.10.0 | linux | x64
node-pre-gyp info check checked for "/home/deploy/backend_staging/releases/2023-11-24-19-15-16-716-UTC/node_modules/node-libcurl/lib/binding/node_libcurl.node" (not found)
node-pre-gyp http GET https://github.com/JCMais/node-libcurl/releases/download/v3.0.0/node_libcurl-v3.0.0-node-v115-linux-x64-glibc.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/JCMais/node-libcurl/releases/download/v3.0.0/node_libcurl-v3.0.0-node-v115-linux-x64-glibc.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for node-libcurl@3.0.0 and node@20.10.0 (node-v115 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/JCMais/node-libcurl/releases/download/v3.0.0/node_libcurl-v3.0.0-node-v115-linux-x64-glibc.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.0
gyp info using node@20.10.0 | linux | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.0
gyp info using node@20.10.0 | linux | x64
gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/deploy/backend_staging/releases/2023-11-24-19-15-16-716-UTC/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/deploy/backend_staging/releases/2023-11-24-19-15-16-716-UTC/node_modules/node-libcurl/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/deploy/backend_staging/releases/2023-11-24-19-15-16-716-UTC/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/deploy/.cache/node-gyp/20.10.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/deploy/.cache/node-gyp/20.10.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/deploy/backend_staging/releases/2023-11-24-19-15-16-716-UTC/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/deploy/.cache/node-gyp/20.10.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/deploy/backend_staging/releases/2023-11-24-19-15-16-716-UTC/node_modules/node-libcurl',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.0
gyp info using node@20.10.0 | linux | x64
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/home/deploy/backend_staging/releases/2023-11-24-19-15-16-716-UTC/node_modules/which/which.js:10:17)
gyp ERR! stack     at /home/deploy/backend_staging/releases/2023-11-24-19-15-16-716-UTC/node_modules/which/which.js:57:18
gyp ERR! stack     at new Promise (<anonymous>)
gyp ERR! stack     at step (/home/deploy/backend_staging/releases/2023-11-24-19-15-16-716-UTC/node_modules/which/which.js:54:21)
gyp ERR! stack     at /home/deploy/backend_staging/releases/2023-11-24-19-15-16-716-UTC/node_modules/which/which.js:71:22
gyp ERR! stack     at new Promise (<anonymous>)
gyp ERR! stack     at subStep (/home/deploy/backend_staging/releases/2023-11-24-19-15-16-716-UTC/node_modules/which/which.js:69:33)
gyp ERR! stack     at /home/deploy/backend_staging/releases/2023-11-24-19-15-16-716-UTC/node_modules/which/which.js:80:22
gyp ERR! stack     at /home/deploy/backend_staging/releases/2023-11-24-19-15-16-716-UTC/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /home/deploy/backend_staging/releases/2023-11-24-19-15-16-716-UTC/node_modules/isexe/mode.js:8:5
gyp ERR! System Linux 5.4.0-166-generic
gyp ERR! command "/usr/local/bin/node" "/home/deploy/backend_staging/releases/2023-11-24-19-15-16-716-UTC/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/deploy/backend_staging/releases/2023-11-24-19-15-16-716-UTC/node_modules/node-libcurl/lib/binding/node_libcurl.node" "--module_name=node_libcurl" "--module_path=/home/deploy/backend_staging/releases/2023-11-24-19-15-16-716-UTC/node_modules/node-libcurl/lib/binding" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v115"
gyp ERR! cwd /home/deploy/backend_staging/releases/2023-11-24-19-15-16-716-UTC/node_modules/node-libcurl
gyp ERR! node -v v20.10.0
gyp ERR! node-gyp -v v9.3.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /home/deploy/backend_staging/releases/2023-11-24-19-15-16-716-UTC/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/deploy/backend_staging/releases/2023-11-24-19-15-16-716-UTC/node_modules/node-libcurl/lib/binding/node_libcurl.node --module_name=node_libcurl --module_path=/home/deploy/backend_staging/releases/2023-11-24-19-15-16-716-UTC/node_modules/node-libcurl/lib/binding --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v115' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/deploy/backend_staging/releases/2023-11-24-19-15-16-716-UTC/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
node-pre-gyp ERR! System Linux 5.4.0-166-generic
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/deploy/backend_staging/releases/2023-11-24-19-15-16-716-UTC/node_modules/node-libcurl/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/deploy/backend_staging/releases/2023-11-24-19-15-16-716-UTC/node_modules/node-libcurl
node-pre-gyp ERR! node -v v20.10.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.10
node-pre-gyp ERR! not ok 
```

Especially this lines shows, that the Linked Packages is not available for download (404) and it give a try to compile from source... which at least fail with missing make-binaries at the server:
```
node-pre-gyp info check checked for "/home/deploy/backend_staging/releases/2023-11-24-19-15-16-716-UTC/node_modules/node-libcurl/lib/binding/node_libcurl.node" (not found)
node-pre-gyp http GET https://github.com/JCMais/node-libcurl/releases/download/v3.0.0/node_libcurl-v3.0.0-node-v115-linux-x64-glibc.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/JCMais/node-libcurl/releases/download/v3.0.0/node_libcurl-v3.0.0-node-v115-linux-x64-glibc.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for node-libcurl@3.0.0 and node@20.10.0 (node-v115 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/JCMais/node-libcurl/releases/download/v3.0.0/node_libcurl-v3.0.0-node-v115-linux-x64-glibc.tar.gz

...
gyp ERR! build error 
gyp ERR! stack Error: not found: make
```

@JCMais can you fix the broken `release-download-path` please? 
Isse seems to be caused of a naming-missmatch : 
![image](https://github.com/JCMais/node-libcurl/assets/1778068/d1357ade-eadb-43dd-bda5-16ee1bdd9773)

**Comment by JCMais** [comment]
@xstable the error here is that there are no prebuilt binaries for v20, I'm trying to get it done, but finding time to work on this has been harder than I expected.

Follow https://github.com/JCMais/node-libcurl/issues/399 for updates.
