### ISSUE TITLE
Error: /lib64/libc.so.6: version `GLIBC_2.14' not found

### ISSUE THREAD

**Issue by ali-khabbaz** [JCMais/node-libcurl#45]
Hi
i'm using Centos 6.6(Final), when using module i got the following error : 

Error: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /root/node_modules/node-libcurl/lib/binding/node_libcurl.node)

**Comment by JCMais** [comment]
Try updating the package ``glibc-devel``

**Comment by ali-khabbaz** [comment]
afer running "npm install node-libcurl --build-from-source"

i got the following errors : 

cc1plus: error: unrecognized command line option "-std=c++11"
cc1plus: warning: unrecognized command line option "-Wno-narrowing"
make: *** [Release/obj.target/node_libcurl/src/node_libcurl.o] Error 1
make: Leaving directory `/root/node_modules/node-libcurl/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2

**Comment by JCMais** [comment]
Update gcc.

**Comment by maddo7** [comment]
Was somebody able to resolve this issue? I'm currently having troubles with it.
I installed the devtools-2 and ran `scl enable devtoolset-2 bash`,  `gcc --version` shows
`gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)` but still if I run  `npm install node-libcurl --build-from-source`
 I get 

```
cc1plus: error: unrecognized command line option "-std=c++11"
cc1plus: warning: unrecognized command line option "-Wno-narrowing"

```

**Comment by JCMais** [comment]
This is really strange, since 4.8 has support for c++11. Run ``npm install node-libcurl --build-from-source --verbose``

**Comment by maddo7** [comment]
This gives

```
> node-libcurl@0.7.0 install /home/name/nodeapps/node_modules/node-libcurl
> node-pre-gyp install --fallback-to-build

make: Entering directory `/home/name/nodeapps/node_modules/node-libcurl/build'
  g++ '-DNODE_GYP_MODULE_NAME=node_libcurl' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/root/.node-gyp/0.10.40/include/node -I/root/.node-gyp/0.10.40/src -I/root/.node-gyp/0.10.40/deps/uv/include -I/root/.node-gyp/0.10.40/deps/v8/include -I../node_modules/nan  -fPIC -Wall -Wextra -Wno-unused-parameter -pthread -m64 -std=c++11 -O2 -Wno-narrowing -O2 -fno-strict-aliasing -fno-tree-vrp -fno-tree-sink -fno-omit-frame-pointer -fno-rtti -fno-exceptions -MMD -MF ./Release/.deps/Release/obj.target/node_libcurl/src/node_libcurl.o.d.raw  -c -o Release/obj.target/node_libcurl/src/node_libcurl.o ../src/node_libcurl.cc
make: Leaving directory `/home/name/nodeapps/node_modules/node-libcurl/build'
Failed to execute '/usr/bin/node /home/name/nodeapps/node_modules/node-libcurl/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/name/nodeapps/node_modules/node-libcurl/lib/binding/node_libcurl.node --module_name=node_libcurl --module_path=/home/name/nodeapps/node_modules/node-libcurl/lib/binding' (1)
```

**Comment by JCMais** [comment]
That is the full log? Because if yes I don't think I can help, the log is not showing anything useful.

Anyway, about the last error, if you can find where the binaries for the gcc 4.8 are located, you can:

```
export CC=/path/to/gcc
export CXX=/path/to/g++
npm install node-libcurl --build-from-source
```

This would fix any issue caused by wrong gcc version being used (if you have multiple ones installed)

**Comment by maddo7** [comment]
Strangely even when running these export commands with the right path nothing changed.
Ther's more output with the verbose option but it seems I can't send the output to a file so some part is missing:

http://pastebin.com/tRseCus5

Other than that I have the npm-debug.log from the command

**Comment by maddo7** [comment]
It seems g++ was missing, once I got that the error wasn't present anymore. Now I've got another issue:

```
../src/Easy.cc:610:34: error: ‘CURLE_UNKNOWN_OPTION’ was not declared in this scope
         CURLcode setOptRetCode = CURLE_UNKNOWN_OPTION;
                                  ^
make: *** [Release/obj.target/node_libcurl/src/Easy.o] Error 1
make: Leaving directory `/home/name/nodeapps/node_modules/node-libcurl/build'
gyp ERR! build error
```

Full error:

```
> node-pre-gyp install --fallback-to-build

make: Entering directory `/home/name/nodeapps/node_modules/node-libcurl/build'
  CXX(target) Release/obj.target/node_libcurl/src/node_libcurl.o
  CXX(target) Release/obj.target/node_libcurl/src/Easy.o
../src/Easy.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE NodeLibcurl::Easy::SetOpt(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/Easy.cc:610:34: error: ‘CURLE_UNKNOWN_OPTION’ was not declared in this scope
         CURLcode setOptRetCode = CURLE_UNKNOWN_OPTION;
                                  ^
make: *** [Release/obj.target/node_libcurl/src/Easy.o] Error 1
make: Leaving directory `/home/name/nodeapps/node_modules/node-libcurl/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/name/nodeapps/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 2.6.32-504.12.2.el6.x86_64
gyp ERR! command "/usr/local/bin/node" "/home/name/nodeapps/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/name/nodeapps/node_modules/node-libcurl/lib/binding/node_libcurl.node" "--module_name=node_libcurl" "--module_path=/home/name/nodeapps/node_modules/node-libcurl/lib/binding"
gyp ERR! cwd /home/name/nodeapps/node_modules/node-libcurl
gyp ERR! node -v v5.4.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /home/name/nodeapps/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/name/nodeapps/node_modules/node-libcurl/lib/binding/node_libcurl.node --module_name=node_libcurl --module_path=/home/name/nodeapps/node_modules/node-libcurl/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/name/nodeapps/node_modules/node-libcurl/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:821:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 2.6.32-504.12.2.el6.x86_64
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/name/nodeapps/node_modules/node-libcurl/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/name/nodeapps/node_modules/node-libcurl
node-pre-gyp ERR! node -v v5.4.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.11
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /home/name/nodeapps/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/name/nodeapps/node_modules/node-libcurl/lib/binding/node_libcurl.node --module_name=node_libcurl --module_path=/home/name/nodeapps/node_modules/node-libcurl/lib/binding' (1)
npm WARN nodeapps@1.0.0 No repository field.
npm ERR! Linux 2.6.32-504.12.2.el6.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/bin/npm" "install" "node-libcurl" "--build-from-source"
npm ERR! node v5.4.1
npm ERR! npm  v3.7.2
npm ERR! code ELIFECYCLE

npm ERR! node-libcurl@0.7.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-libcurl@0.7.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-libcurl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-libcurl
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-libcurl
npm ERR! There is likely additional logging output above.
```

**Comment by JCMais** [comment]
no more errors, you got it running? :smile:

**Comment by maddo7** [comment]
Yes, everything fine now.

**Comment by JCMais** [comment]
Nice to hear.
