### ISSUE TITLE
install: node-pre-gyp install --fallback-to-build

### ISSUE THREAD

**Issue by gagalago** [JCMais/node-libcurl#60]
I have an error during the installation phase. 
Just for information, I have an ArchLinux: Linux sigo-laptop 4.5.2-1-ARCH #1 SMP PREEMPT Thu Apr 21 18:21:27 CEST 2016 x86_64 GNU/Linux
node version: v6.1.0

the stacktrace
```
> node-libcurl@0.7.0 install /home/sigo/workspace/sortlist/node_modules/node-libcurl
> node-pre-gyp install --fallback-to-build

make : on entre dans le répertoire « /home/sigo/workspace/sortlist/node_modules/node-libcurl/build »
  CXX(target) Release/obj.target/node_libcurl/src/node_libcurl.o
In file included from ../src/node_libcurl.cc:25:0:
../../nan/nan.h:590:20: erreur : variable or field ‘AddGCEpilogueCallback’ declared void
       v8::Isolate::GCEpilogueCallback callback
                    ^~~~~~~~~~~~~~~~~~
../../nan/nan.h:590:7: erreur : ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCEpilogueCallback callback
       ^~
../../nan/nan.h:591:18: erreur : expected primary-expression before ‘gc_type_filter’
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^~~~~~~~~~~~~~
../../nan/nan.h:596:20: erreur : variable or field ‘RemoveGCEpilogueCallback’ declared void
       v8::Isolate::GCEpilogueCallback callback) {
                    ^~~~~~~~~~~~~~~~~~
../../nan/nan.h:596:7: erreur : ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCEpilogueCallback callback) {
       ^~
../../nan/nan.h:601:20: erreur : variable or field ‘AddGCPrologueCallback’ declared void
       v8::Isolate::GCPrologueCallback callback
                    ^~~~~~~~~~~~~~~~~~
../../nan/nan.h:601:7: erreur : ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCPrologueCallback callback
       ^~
../../nan/nan.h:602:18: erreur : expected primary-expression before ‘gc_type_filter’
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^~~~~~~~~~~~~~
../../nan/nan.h:607:20: erreur : variable or field ‘RemoveGCPrologueCallback’ declared void
       v8::Isolate::GCPrologueCallback callback) {
                    ^~~~~~~~~~~~~~~~~~
../../nan/nan.h:607:7: erreur : ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCPrologueCallback callback) {
       ^~
node_libcurl.target.mk:100 : la recette pour la cible « Release/obj.target/node_libcurl/src/node_libcurl.o » a échouée
make: *** [Release/obj.target/node_libcurl/src/node_libcurl.o] Erreur 1
make : on quitte le répertoire « /home/sigo/workspace/sortlist/node_modules/node-libcurl/build »
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/sigo/workspace/sortlist/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.5.2-1-ARCH
gyp ERR! command "/usr/bin/node" "/home/sigo/workspace/sortlist/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/sigo/workspace/sortlist/node_modules/node-libcurl/lib/binding/node_libcurl.node" "--module_name=node_libcurl" "--module_path=/home/sigo/workspace/sortlist/node_modules/node-libcurl/lib/binding"
gyp ERR! cwd /home/sigo/workspace/sortlist/node_modules/node-libcurl
gyp ERR! node -v v6.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /home/sigo/workspace/sortlist/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/sigo/workspace/sortlist/node_modules/node-libcurl/lib/binding/node_libcurl.node --module_name=node_libcurl --module_path=/home/sigo/workspace/sortlist/node_modules/node-libcurl/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/sigo/workspace/sortlist/node_modules/node-libcurl/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:850:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
node-pre-gyp ERR! System Linux 4.5.2-1-ARCH
node-pre-gyp ERR! command "/usr/bin/node" "/home/sigo/workspace/sortlist/node_modules/node-libcurl/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/sigo/workspace/sortlist/node_modules/node-libcurl
node-pre-gyp ERR! node -v v6.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.11
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /home/sigo/workspace/sortlist/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/sigo/workspace/sortlist/node_modules/node-libcurl/lib/binding/node_libcurl.node --module_name=node_libcurl --module_path=/home/sigo/workspace/sortlist/node_modules/node-libcurl/lib/binding' (1)
sortlist@0.1.0 /home/sigo/workspace/sortlist
`-- node-pre-gyp@0.6.28  extraneous

npm WARN sortlist@0.1.0 No repository field.
npm WARN sortlist@0.1.0 No license field.
npm ERR! Linux 4.5.2-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "update"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE

npm ERR! node-libcurl@0.7.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
```

What other info, is needed ?

**Comment by JCMais** [comment]
Looks like I need to update [NAN](https://github.com/nodejs/nan).

Will do so later today.

**Comment by JCMais** [comment]
I just installed the addon on node.js v6.1.0 without modifying anything.

Can you install the latest version? You are using version v0.7.0 which is outdated.
