### ISSUE TITLE
Can't install on RedHat

### ISSUE THREAD

**Issue by born2net** [JCMais/node-libcurl#62]
updated my gcc as well as lib and still same error:

```
 node-libcurl@0.9.0 install /var/www/sites/dynasite/htdocs/_msportal/_js/_node/node_modules/node-libcurl
> node-pre-gyp install --fallback-to-build

[node-libcurl] Success: "/var/www/sites/dynasite/htdocs/_msportal/_js/_node/node_modules/node-libcurl/lib/binding/node_libcurl.node" is installed via remote
npm WARN unmet dependency /var/www/sites/dynasite/htdocs/_msportal/_js/_node/node_modules/npm requires npm-registry-client@'~3.2.4' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /var/www/sites/dynasite/htdocs/_msportal/_js/_node/node_modules/npm requires request@'~2.46.0' but will load
npm WARN unmet dependency /var/www/sites/dynasite/htdocs/_msportal/_js/_node/node_modules/request,
npm WARN unmet dependency which is version 2.22.0
npm WARN unmet dependency /var/www/sites/dynasite/htdocs/_msportal/_js/_node/node_modules/npm requires write-file-atomic@'~1.1.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /var/www/sites/dynasite/htdocs/_msportal/_js/_node/node_modules/express.bk/node_modules/finalhandler requires debug@'~2.0.0' but will load
npm WARN unmet dependency /var/www/sites/dynasite/htdocs/_msportal/_js/_node/node_modules/express.bk/node_modules/debug,
npm WARN unmet dependency which is version 0.7.2
npm WARN unmet dependency /var/www/sites/dynasite/htdocs/_msportal/_js/_node/node_modules/express.bk/node_modules/serve-static requires send@'0.9.3' but will load
npm WARN unmet dependency /var/www/sites/dynasite/htdocs/_msportal/_js/_node/node_modules/express.bk/node_modules/send,
npm WARN unmet dependency which is version 0.1.3
node-libcurl@0.9.0 node_modules/node-libcurl
├── bindings@1.2.1
├── debug@2.2.0 (ms@0.7.1)
├── nan@2.2.1
├── npmlog@2.0.3 (ansi@0.3.1, gauge@1.2.7, are-we-there-yet@1.1.2)
└── node-gyp@3.3.1 (graceful-fs@4.1.4, tar@2.2.1, rimraf@2.5.2, path-array@1.0.1)
/var/www/sites/dynasite/htdocs/_msportal/_js/_node->
```

and from source

```
_msportal/_js/_node/node_modules/node-libcurl/lib/binding"
gyp ERR! cwd /var/www/sites/dynasite/htdocs/_msportal/_js/_node/node_modules/node-libcurl
gyp ERR! node -v v4.4.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /var/www/sites/dynasite/htdocs/_msportal/_js/_node/node_modules/node-libcurl/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/var/www/sites/dynasite/htdocs/_msportal/_js/_node/node_modules/node-libcurl/lib/binding/node_libcurl.node --module_name=node_libcurl --module_path=/var/www/sites/dynasite/htdocs/_msportal/_js/_node/node_modules/node-libcurl/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/var/www/sites/dynasite/htdocs/_msportal/_js/_node/node_modules/node-libcurl/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 2.6.32-358.el6.x86_64
node-pre-gyp ERR! command "/usr/local/bin/node" "/var/www/sites/dynasite/htdocs/_msportal/_js/_node/node_modules/node-libcurl/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"

node-pre-gyp ERR! cwd /var/www/sites/dynasite/htdocs/_msportal/_js/_node/node_modules/node-libcurl
node-pre-gyp ERR! node -v v4.4.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.13
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /var/www/sites/dynasite/htdocs/_msportal/_js/_node/node_modules/node-libcurl/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/var/www/sites/dynasite/htdocs/_msportal/_js/_node/node_modules/node-libcurl/lib/binding/node_libcurl.node --module_name=node_libcurl --module_path=/var/www/sites/dynasite/htdocs/_msportal/_js/_node/node_modules/node-libcurl/lib/binding' (1)
npm ERR! Linux 2.6.32-358.el6.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-libcurl" "--build-from-source"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! code ELIFECYCLE

npm ERR! node-libcurl@0.9.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-libcurl@0.9.0 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the node-libcurl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-libcurl
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls node-libcurl
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/sites/dynasite/htdocs/_msportal/_js/_node/npm-debug.log
```

any help is appreciated

Sean

**Comment by born2net** [comment]
and when I try and load

```
> var Curl = require( 'node-libcurl' ).Curl;
Error: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /var/www/sites/dynasite/htdocs/_msportal/_js/_node/node_modules/node-libcurl/lib/binding/node_libcurl.node)
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/sites/dynasite/htdocs/_msportal/_js/_node/node_modules/node-libcurl/lib/Easy.js:39:29)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
```

**Comment by born2net** [comment]
and glibc

```
Loaded plugins: amazon-id, rhui-lb, security
Setting up Install Process
Package glibc-2.12-1.192.el6.x86_64 already installed and latest version
Nothing to do
```

**Comment by born2net** [comment]
ended up using diff lib solution
regards
