### ISSUE TITLE
Binaries 404 with node-libcurl

### ISSUE THREAD

**Issue by thekettu** [JCMais/node-libcurl#82]
Installing node-libcurl via the provided instructions for Electron seem to 404:

```
$ npm install node-libcurl --runtime=electron --target=1.6.1 --disturl=https://atom.io/download/atom-shell --arch=x64 --save             
npm WARN prefer global node-gyp@3.5.0 should be installed with -g

> node-libcurl@1.1.0 install /path/to/node_modules/node-libcurl
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://github.com/JCMais/node-libcurl/releases/download/v1.1.0/node_libcurl-v1.1.0-electron-v1.6-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-libcurl@1.1.0 and electron@1.6.1 (electron-v1.6 ABI) (falling back to source compile with node-gyp)
```

It will attempt to call `make` anyway, but fail with this error if anything requiring node-libcurl is started:

```
Error: Module version mismatch. Expected 50, got 53.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/path/to/node_modules/node-libcurl/lib/Easy.js:40:29)
```

**Comment by JCMais** [comment]
Add ``--build-from-source``

**Comment by thekettu** [comment]
Just did, throws the same `Module version mismatch` error.
