### ISSUE TITLE
Not Working in Centos 6

### ISSUE THREAD

**Issue by fahidmohammad** [JCMais/node-libcurl#86]
**OS**
```
Linux hoPla-batch 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

````
**Nodejs Version**
````
v7.8.0

````

**ERROR**
```
Error: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /usr/local/share/Folder/Folder/node_modules/node-libcurl/lib/binding/node_libcurl.node)
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/share/Folder/Folder/node_modules/node-libcurl/lib/Easy.js:40:29)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

```

Setup was smooth but when i execute the command i got the above error. Also tried with build from source args and **got the below error:**

```
> node-libcurl@1.1.0 install /usr/local/share/Folder/Folder/node_modules/node-libcurl
> node-pre-gyp install --fallback-to-build

make: Entering directory `/usr/local/share/Folder/Folder/node_modules/node-libcurl/build'
  CXX(target) Release/obj.target/node_libcurl/src/node_libcurl.o
cc1plus: error: unrecognized command line option "-std=c++11"
cc1plus: warning: unrecognized command line option "-Wno-narrowing"
make: *** [Release/obj.target/node_libcurl/src/node_libcurl.o] Error 1
make: Leaving directory `/usr/local/share/Folder/Folder/node_modules/node-libcurl/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/share/Folder/Folder/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 2.6.32-431.el6.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/share/Folder/Folder/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/local/share/Folder/Folder/node_modules/node-libcurl/lib/binding/node_libcurl.node" "--module_name=node_libcurl" "--module_path=/usr/local/share/Folder/Folder/node_modules/node-libcurl/lib/binding"
gyp ERR! cwd /usr/local/share/Folder/Folder/node_modules/node-libcurl
gyp ERR! node -v v7.8.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/share/Folder/Folder/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/share/Folder/Folder/node_modules/node-libcurl/lib/binding/node_libcurl.node --module_name=node_libcurl --module_path=/usr/local/share/Folder/Folder/node_modules/node-libcurl/lib/binding' (1)


```

**Comment by JCMais** [comment]
You need to update `glibc`.

**Comment by fahidmohammad** [comment]
After updating `glibc ` package its working fine.
@JCMais Thank you for the support.
